### ISSUE TITLE
I have some problem about the menuhax install failed

### ISSUE THREAD

**Issue by zyxnet0115** [yellows8/3ds_homemenuhax#100]
First,I uninstall the menuhax v2.1,and I need reinstall v2.2,but the program told me,install failed.
the themehax v1.3 or the menuhax v2.1&2.2,all of failed
I have the picture,please .
I use the ninjhax to enter the homebrew,then run the menuhax or themehax,but it's can't be install.
I change the theme to red,blue,black,and change it to white(not use theme),but Useless.
![img_1666](https://cloud.githubusercontent.com/assets/17747255/13641326/fb06ecfa-e652-11e5-966e-dc6b88414241.JPG)
![img_1668](https://cloud.githubusercontent.com/assets/17747255/13641327/fb2b6cce-e652-11e5-9c87-774b7804e573.JPG)

**Comment by zyxnet0115** [comment]
My console is new3ds ver9.1-20J

**Comment by yellows8** [comment]
README
