### ISSUE TITLE
Error 0x0000002

### ISSUE THREAD

**Issue by ricardo8csm** [yellows8/3ds_homemenuhax#102]
Menuhax is giving me an error 0x0000002 at installation. I tried to install it already a couple of times.
I'm using OoTHax on n3DS 10.6.
I created the theme cache by changing themes prior to running menuhax.

This is the error.
![1457803871680](https://cloud.githubusercontent.com/assets/6227782/13724665/efb7ab76-e884-11e5-908f-bbcc575cf73c.jpg)

I've noticed someone else here with this error and they haven't extracted their files properly, but I already tried it with 5 different programs (winzip, winrar, peazip, the default windows one and x-archive on Fedora Linux) already, and there is no EUR24576_new3ds.lz there.

Anything else I should try?

**Comment by yellows8** [comment]
"10.6" README
