### ISSUE TITLE
Error Code 0x00000002 

### ISSUE THREAD

**Issue by NewBowlCut** [yellows8/3ds_homemenuhax#103]
http://i.imgur.com/qLwsw62.jpg

It keeps asking for menuhax_USA25600_old3ds.lz and I swear I don't have that lz file. None of the latest downloads have that file so I dunno what to do. Thanks for the help in advance!!

**Comment by NewBowlCut** [comment]
lol forgot to say, I'm on 10.6.0-31U

**Comment by DAVID2828** [comment]
yes i have the same problem i even google the file nutin came up

**Comment by thedax** [comment]
> I'm on 10.6.0-31U

MenuHax was patched in 10.6.

https://3dbrew.org/wiki/10.6.0-31#Home_Menu

**Comment by Anushiravan** [comment]
Having the same issue, using oot3dhax and then the menuhax manager, but the menuhax_USA25600_old3ds is missing from the \starter\3ds\menuhax_manager\finaloutput\shufflepayload folder, the only one close is the JPN25600 lz file.
