### ISSUE TITLE
Preventing update of 3ds firmware 

### ISSUE THREAD

**Issue by kcruz10** [yellows8/3ds_homemenuhax#105]
How do I prevent my ds from updating to the next firmware? I already tried blocking my DNS from receiving updates from Nintendo. When I need to add friends or use Internet for homebrew it says I need to update before using Internet or adding friends.. Any suggestions???

**Comment by Hartie95** [comment]
It won't update automaticly, but there are some values checked on the server side, which is why you are getting this message.
But yellows8 released this some days ago, and it should help you:
https://github.com/yellows8/ctr-httpwn

**Comment by kcruz10** [comment]
@hartmannaf so do I need to download something else? Because I kept pressing no don't update finally I wasn't able to use Internet and add friends so I updated to 10.7 and can't even use homebrew anymore
