### ISSUE TITLE
HELP GRID LAUNCHER (AKA HOMEBREW LAUNCHER)

### ISSUE THREAD

**Issue by pandemonium-mc** [yellows8/3ds_homemenuhax#106]
So I got up to Part 5 (arm9loaderhax & AuReiNAND) on Plailect's guide and I got into a little trouble. I ran Pasta and that worked then it rebooted and showed the same screen every time I rebooted manually. Then I removed the card and added some files that were not in the steps and was able to get to the AuReiNand configuration menu. The. The same thing happened again where it kept showing up after reboot. Then, I deleted the files of the AuReiNand and menuhax and was able to to get to the sysNAND. Then I ran sliderhax and was able to get into home brew. But then when ever I try to load apps they would launch but then it would bring me back to the home brew. It's weird and I don't get it at all. Usually it shows 1 red screen then another one pops up and bring me back to the home brew. If there is anyone that can help me please reply as soon as possible. Sorry if I don't make any sense I'm kind of a noob at this. If you need pics or a video I'll post them when you comment if you need them.

**Comment by pandemonium-mc** [comment]
Here's the guide I'm using:
https://github.com/Plailect/Guide/wiki/Part-5-(arm9loaderhax-&-AuReiNAND)

**Comment by yellows8** [comment]
Grid-launcher isn't supported here.
