### ISSUE TITLE
error 0xd8e06406 with menuhax

### ISSUE THREAD

**Issue by astyles4** [yellows8/3ds_homemenuhax#107]
I have an O3ds running 9.2.0-20U.  I used cubic ninja and ninjhax to initiate homebrew.  I used the same homebrew starter kit provided in part 1.  Whenever I try to install menuhax, it gives me the error message: 
"failed to initialize am: 0xd8e06406. the AM service is inaccessible. with the hblauncher-payload this should never happen.  this is normal with plain ninjhax v1.x: this app isnt usable form ninjhax v1.x wihtout any further hax.  an error occured if this is an actual issure not related to user failure please report this..."
How do I properly install menuhax?

**Comment by nofearfoda** [comment]
i hav the same problem, some guy tells me to change the 3ds theme after install menuhax but it's doesn't work for me =(

**Comment by Masamune3210** [comment]
Use browserhax, and report back if it still has the issue. https://yls8.mtheall.com/3dsbrowserhax.php
