### ISSUE TITLE
Having access to Internet features with homebrew

### ISSUE THREAD

**Issue by kcruz10** [yellows8/3ds_homemenuhax#108]
I have successfully downgraded from 10.7 > 9.5 ; I can use the browser.. But I can't add friends or use Internet in my game.. I blocked dns from updates etc . How do I go about being downgraded and not getting prompt to update ? Please help

**Comment by yellows8** [comment]
Not menuhax related.

**Comment by ghost** [comment]
@kcruz10 why in the world would you downgrade to 9.5? makes no sense at all.
I can respect the fact that you may not care for piracy, but weird firmware vers. like that have spotty support at best.

**Comment by kcruz10** [comment]
@idgrepthat i don't get what your trying to say.. But I downgraded because I had 10.7 and I play animal crossing new leaf and need save manager to use new leaf tools. You prob have no clue what I'm talking about lol..

**Comment by ghost** [comment]
@kcruz10 with 9.2 you can have everything you want and because emunand, stay online. But go ahead, keep doing things the dumb way. Not my issue.

**Comment by kcruz10** [comment]
@idgrepthat idgrepthat Ooops.. yeah that what i meant i have 9.2..my bad.. anyways.. maybe you can help me. I can do everything i want yes but i cant add people on my friends list. it says i need to update..

**Comment by ghost** [comment]
Use emunand to clone your firmware to the sd card and update to 10.7. You need a cfw to do that, https://gbatemp.net/threads/tutorial-setting-up-9-0-9-2-n3ds-xl-for-cfw-including-emunand-coldboot-cia-installer.405589/ is one of many tutorials on it.

**Comment by kcruz10** [comment]
@idgrepthat  Thank you. I really appreciate it. This is what I have been trying to look for.. thanks so much.
