### ISSUE TITLE
Need a hand, issue installing Menuhax (with screeshots)

### ISSUE THREAD

**Issue by JonathanKA** [yellows8/3ds_homemenuhax#109]
Hi Guys,

My O3DS is at 9.7 and i managed to open the homebrew channel. But im having issues when i try to install the menuhax. Here's the screenshots:

![12922240_987490018013534_176903933_o](https://cloud.githubusercontent.com/assets/8617943/14303855/502417f8-fb84-11e5-9cab-82b5dfe1d597.jpg)

here's how my sd is organized:
![image](https://cloud.githubusercontent.com/assets/8617943/14303864/6769bfee-fb84-11e5-8f57-581dc3dbc9c7.png)
![image](https://cloud.githubusercontent.com/assets/8617943/14303872/78da941a-fb84-11e5-9d59-1cff43ea2fa5.png)
![image](https://cloud.githubusercontent.com/assets/8617943/14303883/88e8bd78-fb84-11e5-8f90-4dbae540fb79.png)

I have tried moving the themepayload folder as you can see above(tried because of another post), but still no luck. Also, before i moved the menuhax_manager folder to the root i tried with is located as SD/3ds/menuhax_manager. Any ideas?

Thanks for your time!

**Comment by yellows8** [comment]
You didn't exact it to SD properly, it's described in the release notes...(Contents of starter.zip should be extracted to SD root)

**Comment by JonathanKA** [comment]
Thank you very much, i just followed a tutorial mindlessly and didnt look at the read me! =\ Gonna fix that later and see if it works
