### ISSUE TITLE
error 0x00000002

### ISSUE THREAD

**Issue by DAVID2828** [yellows8/3ds_homemenuhax#110]
yes i keep geting this error 0x00000002 and i am on 10.0.7.31-u

**Comment by yellows8** [comment]
README

**Comment by DAVID2828** [comment]
what u mean readme

**Comment by itzAlex** [comment]
@DAVID2828 The version 10.7.0 isn't supported by HomeMenuHax. You can do the downgrade to <10.6.0 if you want to use it.

**Comment by DAVID2828** [comment]
i did the downgrade once and my 3ds got hard brick i will not do it agen

**Comment by itzAlex** [comment]
@DAVID2828 The Downgrade is very easy... And the probability for the hard brick is difficult. Last message.

**Comment by DAVID2828** [comment]
well i have allready hard brick my n3ds and Nintendo had to fix it

**Comment by Masamune3210** [comment]
No Downgrade = No HomeMenuHax, Its that simple. If you dont want to downgrade, just use a different entrypoint

**Comment by DAVID2828** [comment]
i have a entrypoint i dont use the browerhax was getting the error with the legend of zelda ocarina of time

**Comment by Masamune3210** [comment]
If you had the error while using oothax, why did you decide to put the issue on the homemenuhax repo?

**Comment by DAVID2828** [comment]
i was trying to install homebrew the site sed i cud use it

**Comment by Masamune3210** [comment]
what site? you can use the homebrew launcher on 10.7 but certain things are incompatible unless you downgrade

**Comment by DAVID2828** [comment]
http://smealum.github.io/3ds/

**Comment by DAVID2828** [comment]
i can get in to homebrew but cant install

**Comment by Masamune3210** [comment]
You dont have to install anything to use it. If you are in the homebrew launcher, you are done with the setup. things like ironhax and menuhax just add another entrypoint to make it easier to return to the launcher

**Comment by DAVID2828** [comment]
for what i want it for yes i do i want it to install gateway card but i need menuhax on my 3ds to do that

**Comment by yellows8** [comment]
Please move this elsewhere.

**Comment by DAVID2828** [comment]
why do people even comment if they are not going to help

**Comment by AlexMobius** [comment]
I have a same problem few minutes ago, and I make the downgrade with no problem, using the SafeSysUpdate, If you can acess the Menuhax without installing him via OoT, you can make de downgrade no problem to install the menuhax. If you need a help, you can call me anytime, I have one more 3ds to do a downgrade.
