### ISSUE TITLE
Error 0x00000002

### ISSUE THREAD

**Issue by Odaxis** [yellows8/3ds_homemenuhax#111]
On a 2DS and using latest firmware 10.7.0-32U and using latest Starter Kit from Smea's page.
Initialized theme data by selecting a theme and removing it.
Accessed Homebrew via OoTHax
Attempting to install menuhax, received error 0x00000002.
![dbgzgqv](https://cloud.githubusercontent.com/assets/18354599/14394085/fac8bfca-fda4-11e5-9b69-b0eb8f1ba3bb.jpg)
I am probably doing something obviously stupid and apologize if I'm wasting your time.

**Comment by yellows8** [comment]
README
