### ISSUE TITLE
Not installable on 10.6.0-31E NEW3DSXL

### ISSUE THREAD

**Issue by Crosant** [yellows8/3ds_homemenuhax#112]
The requested file is only available for the JPN release. It would be nice to have it for the EUR release too.
![b99bbd11-7c21-445d-983c-8b711b1f6f2d](https://cloud.githubusercontent.com/assets/889109/14444572/aa4f2940-0046-11e6-9b6f-d050d61bc2c8.jpg)

**Comment by yellows8** [comment]
~~"only available for the JPN release" wat~~ No, USA and non-USA homemenu use different title-versions.

https://github.com/yellows8/3ds_homemenuhax#vuln-fix-sysupdates

**Comment by Crosant** [comment]
oh I havent seen that :/
