### ISSUE TITLE
error0xd900182f can't get the home menu title-version

### ISSUE THREAD

**Issue by songrunhe** [yellows8/3ds_homemenuhax#114]
Before creating an issue, please make sure that you:
- Properly extracted the _latest_ release-archive to your SD card. https://github.com/yellows8/3ds_homemenuhax/releases
- Read the entire README.

![Uploading 1462443292859.jpg…]()

Note that HTTPC error 0xd8a0a046(and perhaps others) are caused by no usable network connection being available.

**Comment by yellows8** [comment]
https://github.com/yellows8/3ds_homemenuhax#ninjhax-v1x
