### ISSUE TITLE
menuhax instal failed: 0x00000002

### ISSUE THREAD

**Issue by xosogabu** [yellows8/3ds_homemenuhax#116]
old 3ds 10.7.0-32u using ninjahax and extracted the latest release-archive to SD card. 
![fullsizerender](https://cloud.githubusercontent.com/assets/19328857/15218614/1c5f1664-1837-11e6-9537-e3c7d780d527.jpg)

**Comment by yellows8** [comment]
https://github.com/yellows8/3ds_homemenuhax#vuln-fix-sysupdates
