### ISSUE TITLE
Trouble installing Homebrew

### ISSUE THREAD

**Issue by leo5432** [yellows8/3ds_homemenuhax#117]
My main goal is to be able to play Japanese games on my American 3ds. I downloaded the starter kit from the "Preparing your SD card" section on the main page, and read the "read me" instructions, but I'm still having trouble. I'm unsure what to do after putting the files on my SD card. I'm unable to connect to the internet so I'm trying to get the homebrew channel with the "Home Button feature". I've attached a picture of what my SD card looks like currently. 

Thanks so much 
[Doc1.docx](https://github.com/yellows8/3ds_homemenuhax/files/266995/Doc1.docx)

**Comment by yellows8** [comment]
You can't install menuhax(if you're on a supported system-version) unless you can already run homebrew.

What system-version are you on?

**Comment by leo5432** [comment]
Ver. 9.5.0-22U

**Comment by yellows8** [comment]
https://yls8.mtheall.com/3dsbrowserhax.php

**Comment by leo5432** [comment]
It's working great, thank you so much
