### ISSUE TITLE
Installation failed (error 0x00000002)

### ISSUE THREAD

**Issue by Schrax** [yellows8/3ds_homemenuhax#121]
installation fails every time i try to install menuhax 2.2.
I've the latest files and I correctly extracted files to the /3ds/ folder

**Comment by yellows8** [comment]
https://github.com/yellows8/3ds_homemenuhax#vuln-fix-sysupdates

**Comment by Schrax** [comment]
My frimware is 10.7.0-32E

**Comment by yellows8** [comment]
README

**Comment by Schrax** [comment]
ok

**Comment by Schrax** [comment]
if you can translate that in french it would be easyier for me or if you can't do it please explicate that to me
