### ISSUE TITLE
Solved

### ISSUE THREAD

**Issue by lshprung** [yellows8/3ds_homemenuhax#122]
Before creating an issue, please make sure that you:
- Properly extracted the _latest_ release-archive to your SD card. https://github.com/yellows8/3ds_homemenuhax/releases
- Read the entire README.

Note that HTTPC error 0xd8a0a046(and perhaps others) are caused by no usable network connection being available.

**Comment by yellows8** [comment]
How about actually including a screenshot in the issue instead of the issue-template...(+ what menuhax version)

**Comment by lshprung** [comment]
![menuhax error](https://cloud.githubusercontent.com/assets/19890952/15991893/852f24c2-3074-11e6-8085-11750e168ce4.JPG)

**Comment by lshprung** [comment]
Never mind, turns out all I had to do was to put the /3ds/ folder outside of the /Nintendo 3ds/ folder
