### ISSUE TITLE
Menuhax install error

### ISSUE THREAD

**Issue by JeonHyungJun** [yellows8/3ds_homemenuhax#124]
Before creating an issue, please make sure that you:

N3ds 9.2.0U menuhax install button Click
Error messages of installed 
Getting system-version/system-info etc....
Using Home Menu programID: 0x0004003000008f02.
Failed to get the Home menu title-version : 0xd900182f
Install failed : 0xd900182f

Help~!
What is my problem?

**Comment by yellows8** [comment]
https://github.com/yellows8/3ds_homemenuhax#ninjhax-v1x
