### ISSUE TITLE
Menuhax_Manager v2.2 won't install menuhax on my homebrewed 3ds 11.0.0-33u

### ISSUE THREAD

**Issue by Jbols** [yellows8/3ds_homemenuhax#125]
whenever I try installing menuhax_manager, it always says failed "Failed to get the filesize of the body-filepath: sdmc:/3ds/menuhax_manager/finaloutput/shufflepayload/menuhax_USA25600_old3ds. lz" I'm not sure what this error means or how to fix it, may I please get some help?

**Comment by yellows8** [comment]
https://github.com/yellows8/3ds_homemenuhax#vuln-fix-sysupdates

**Comment by Jbols** [comment]
does that mean it's not supported with 11.0.0-33u?

**Comment by yellows8** [comment]
Of course.
