### ISSUE TITLE
error 0x00000002 on n3ds installing menuhax

### ISSUE THREAD

**Issue by almax22** [yellows8/3ds_homemenuhax#126]
when trying to install menuhax onto my new 3ds im getting a few errors:
Failed to get the filesize of the body-filepath: sdmc :/3ds/menuhax_manager/finaloutput/shufflepayload/menuhax_USA25600_new3ds.lz

it says to verify if i have that file location on my SD card but I dont have that lz file on my SD card. I downloaded the latest menuhax zip v2.2 and the starter from https://github.com/Plailect/Guide/wiki/Part-1-(Homebrew)
I dont know if my 3ds is so new that you guys didnt make a payload for it yet.

then is says if i have .lz files in my theme payload which i do.

i tried changing themes and installing them theme over and over again but still same results.

Im lost as this never happened to me, I have installed CFW fully before on my old 3ds no problems

**Comment by yellows8** [comment]
https://github.com/yellows8/3ds_homemenuhax#vuln-fix-sysupdates
