### ISSUE TITLE
i can't uninstall it

### ISSUE THREAD

**Issue by juandiegorojassaldarriaga** [yellows8/3ds_homemenuhax#127]
![20160722_174541 1](https://cloud.githubusercontent.com/assets/20605152/17073330/7a489558-5035-11e6-9d7f-b60ff583f394.jpg)

someone help please, i can't unintall it and i don't know what to do

**Comment by yellows8** [comment]
Actually read the text....(Not sure if you really meant uninstall or install...)

**Comment by juandiegorojassaldarriaga** [comment]
uninstall, it's a "step", the man of the video says that is for "not having future problems"
so when i push it, for uninstalling it shows that and i dont know if it is necesary or not

**Comment by Margen67** [comment]
Video guides can become outdated. You should use [text guides like this one](https://3ds.hacks.guide/) instead.
