### ISSUE TITLE
file "menuhax_USA25600_new3ds.lz" in shufflepayload folder missing, cant install

### ISSUE THREAD

**Issue by AlfonzoFrejoles** [yellows8/3ds_homemenuhax#128]
![20160724_220429](https://cloud.githubusercontent.com/assets/20632405/17088546/b7f09098-51ea-11e6-96fc-87ea67f39482.jpg)
cant install due to a missing file, what should i do?

**Comment by yellows8** [comment]
https://github.com/yellows8/3ds_homemenuhax#vuln-fix-sysupdates

"what should i do?" With v2.2, nothing.

**Comment by AlfonzoFrejoles** [comment]
so, what you're saying is i cant install it at all?

**Comment by yellows8** [comment]
With v2.2 no.

**Comment by yellows8** [comment]
With v2.2 no.
