### ISSUE TITLE
Can't access eshop from home brew menu

### ISSUE THREAD

**Issue by TrickiestBlock** [yellows8/3ds_homemenuhax#129]
Before creating an issue, please make sure that you:
- Properly extracted the _latest_ release-archive to your SD card. https://github.com/yellows8/3ds_homemenuhax/releases
- Read the entire README.

Note that HTTPC error 0xd8a0a046(and perhaps others) are caused by no usable network connection being available.

**Comment by yellows8** [comment]
........
