### ISSUE TITLE
When downloading config via HTTPC, it says that the download failed, with the error code 0xd8a0a049, then it tries to load it from sd and and error code (0x0000002) appears. why is this happening? ussing fw 11 with latest release archive and browser hax

### ISSUE THREAD

**Issue by axeldex** [yellows8/3ds_homemenuhax#130]
Before creating an issue, please make sure that you:
- Properly extracted the _latest_ release-archive to your SD card. https://github.com/yellows8/3ds_homemenuhax/releases
- Read the entire README.

Note that HTTPC error 0xd8a0a046(and perhaps others) are caused by no usable network connection being available.

**Comment by TheMrDew** [comment]
So what in the readme does it specifically say something about this.

Before replying telling some to do what they have already done, make sure you know what you're actually talking about.

**Comment by yellows8** [comment]
Please use the actual issue-post for what it's meant for...(Network fail @ 0xd8a0a049)

**Comment by yellows8** [comment]
#132
