### ISSUE TITLE
After installing menuhax, all home menu icons are gift boxes. This repeats every restart.

### ISSUE THREAD

**Issue by ghost** [yellows8/3ds_homemenuhax#134]
After menuhax was installed on my 11.0.0.-33U New3DSXL, every time I sstart up the 3DS all my icons are in gift boxes again. Not sure why. Also when I try to delete menuhax via the manager, it gives me an error instantly.

**Comment by Kygdom** [comment]
Whoops while i was writing my issue you wrote yours ^^"
Should i delete mine or ?

**Comment by ghost** [comment]
Yours I guess.
Also is the issue because I installed menuhax when I was on no theme selected?

**Comment by Dharengo** [comment]
I had the same problem, but I was able to delete menuhax.

**Comment by yellows8** [comment]
"Also when I try to delete menuhax via the manager, it gives me an error instantly." README

**Comment by yellows8** [comment]
How many official SD titles do you have installed?

I haven't noticed this with latest menuhax(not sure about older pre-release versions), but tbh most of my titles are already presents anyway due to deleting Home Menu extdata a lot.

**Comment by Dharengo** [comment]
As for me, quite a lot, at least 10-15 or so, maybe more.

And I'm using the latest version (due to browserhax having become available again).

Basically, when I press the power button to put it into standby mode, close the 3DS and then open it up again, it gives me an "initial" screen with no theme and all of my apps are "packed". If, however, I power down the 3DS entirely and boot it up normally, I do get them all "unpacked", along with the theme that was active last. However, if I try to change something about the layout (move apps around, move them into folders, etc.), the next time I boot up the 3DS, everything will have reset to its initial state.

**Comment by yellows8** [comment]
"Basically, when I press the power button to put it into standby mode, close the 3DS and then open it up again," That's normal. But there's no reason to enter that screen just for sleep-mode.

"However, if I try to change something about the layout ..." README

**Comment by Dharengo** [comment]
I am afraid I have skimmed the readme several times now. Maybe I just don't understand.

**Comment by Kygdom** [comment]
I have the exact same problems (even if i don't change anything about the layout). Whenever i hit the power button to shut it down or put it into sleep mode, the gift boxs happen again. They were open before installing menuhax btw.

**Comment by Dharengo** [comment]
I think what @yellows8 just meant to say was that this is normal behavior. Either don't put it into standby mode (instead, just close the screen), or power down the 3DS entirely.

**Comment by Kygdom** [comment]
"power down the 3DS entirely"
This is what i do tho ??? Is it normal even then ?

**Comment by Dharengo** [comment]
Oh really? Sorry then, I was under the impression that you just pressed the power button and closed the unit.

**Comment by yellows8** [comment]
So are _all_ of your titles presents even with a hard-boot as soon as Home Menu first loads?

**Comment by ghost** [comment]
All of my titles are there, just in present boxes.

**Comment by ghost** [comment]
Got it working. Booted into menuhax from startup and deleted it from there, swapped to a theme instead of no theme and opened the present boxes ahead of time, reinstalled and we're all good.

**Comment by Kygdom** [comment]
I wanted to try that but i can't choose a color theme for my 3ds anymore so i can't do this.

**Comment by yellows8** [comment]
" i can't choose a color theme for my 3ds anymore" README
