### ISSUE TITLE
After installing menuhax, each time i turn on my 3DS some apps go back to being presents.

### ISSUE THREAD

**Issue by Kygdom** [yellows8/3ds_homemenuhax#135]
After my SaveData.dat problem was resolved i installed menuhax (i forgot to put which color i wanted for my 3ds theme and can't change it anymore but at the limit that's alright), but now each time i turn on my 3DS some specific apps (which i think may be the ones on the SD card) turn back to being presents i have to open. Is there a way to fix it ?

**Comment by Dharengo** [comment]
Same problem. It caused me to uninstall menuhax altogether.

Seems to be a read/write issue or some jazz.

**Comment by yellows8** [comment]
#134
