### ISSUE TITLE
unable to delete menuhax because it is not working

### ISSUE THREAD

**Issue by rumble1234** [yellows8/3ds_homemenuhax#136]
![image](https://cloud.githubusercontent.com/assets/20702353/17219157/ed80aba0-551c-11e6-9747-87670f4a3d80.jpeg)
i having a problem with the menuhax, using the manager 3.0 to install, it install sucessfully within a few sec which is weird and i try to boot up the homebrew but i was unable to boot it up. Instead my 3ds appear a message indicating that (_Error Message: Error Has Occurred. Hold down the Power Button to turn the power off._) i tried to delete the menuhax using the manager but it occur another error stating that (_Deletion failed: 0xc92044e6_) Any suggestion i can make the menuhax work or even remove it??

**Comment by yellows8** [comment]
README

**Comment by rumble1234** [comment]
i have read through the README, but i still not quite understand how the whole thing works and also causing this problem, i install it using the manager while is on no-theme settings.( i guess is this the part went wrong?) . After this error happened, i have tried to delete it or install it, it will give me this error. Changing to basic black theme and tried to delete it same situation. However when is on the main menu of the menuhax manager, it was say that i have successfully installed it which i doubt so. I cant boot up the homebrew when i power on the 3ds and hold L at the same time. It will give me this error which i stated on my previous comment  (Error Message: Error Has Occurred. Hold down the Power Button to turn the power off.) By the way i am using oot3dhax. Thank you for taking the time to reply and address my situation :)

**Comment by yellows8** [comment]
"Error Message: Error Has Occurred.  ..." <- This is after menuhax displays gfx right?

**Comment by rumble1234** [comment]
this is when i power on my 3ds and hold L at the same time, it will load around a few sec and appear that error message, when i go back to the manager to install it again, it came out the error as shown in the picture. For deletion and installing will come out the error as shown in the picture.

**Comment by yellows8** [comment]
"after menuhax displays gfx right?"

**Comment by rumble1234** [comment]
nope it did not even have menuhax displays gfx, it just show the crash screen and go straight to the error message

**Comment by yellows8** [comment]
Are you certain you're using the default PAD config? And you're certain that both screens were all-black before the fatal-error?

**Comment by rumble1234** [comment]
Yes

**Comment by rumble1234** [comment]
just an update, i have managed to delete menuhax and reinstall sucessfully by deleting this following folder in my sd card (SD Card\Nintendo 3DS\random numers and letters\random numers and letters\extdata\00000000\000002cd) 
(SD Card\Nintendo 3DS\random numers and letters\random numers and letters\extdata\00000000\0000008f)
and reinstalling it again. Now my menuhax is working!!
Last question will the menuhax be patched in the future if i dont update or do anything?? Cuz my main entry to homebrew is using oot3dhax

**Comment by yellows8** [comment]
"Last question will the menuhax be patched in the future **if i dont update or do anything**?? " No.
