### ISSUE TITLE
ROPKIT_PATH not set in default build

### ISSUE THREAD

**Issue by mariogamer2** [yellows8/3ds_homemenuhax#138]
When running make defaultbuild,it say:

Makefile:45: **\* "ROPKIT_PATH is not set.".

Checking ["defaultbuild" in makefile](https://github.com/yellows8/3ds_homemenuhax/blob/master/Makefile#L126),it seem it was forgotten.

**Comment by yellows8** [comment]
No, it's user-specified.

**Comment by mariogamer2** [comment]
Sorry...But I do not found anything in Building.md...

**Comment by yellows8** [comment]
https://github.com/yellows8/3ds_ropkit

Why are you building manually anyway?

**Comment by mariogamer2** [comment]
Thank.

Just like this :)
