### ISSUE TITLE
No icon.png for themehax_installer in the repo

### ISSUE THREAD

**Issue by justinkb** [yellows8/3ds_homemenuhax#14]
Minor issue, since building with NO_SMDH obviously works fine, tho.

Just thought I'd create this ticket so it's "out there"

**Comment by yellows8** [comment]
It's obviously using the default icon from ctrulib with the original Makefile atm.

**Comment by justinkb** [comment]
My distro's ctrulib package doesn't include that png, it seems. I'll take
it up with them.

Cheers
