### ISSUE TITLE
Install error

### ISSUE THREAD

**Issue by ghost** [yellows8/3ds_homemenuhax#140]
This is what was written

Checking for the input payload on SD
Requesting the actual payload with http
Writing the menuropbin to SD, to the following path: sdmc:/ropbinpayload_menuhax_USA25600_old3ds.bin

Installing shufflehax
Enabling shuffle temecache
Reading SaveData.dat
Writing updated SaveData.dat
Installing to the SD theme-cache
Failed to get the filesize of the body-filepath: sdmc:/3ds/menuhax_manager/finaloutput/shufflepayload/menuhax_USA25600_old3ds.lz
Verify that you have a menuhax build for your system on SD card: make sure that the release archive you're using actually includes builds for your system-version.
Also verify that the following directory containing .lz files actually existis on your SD card: '/3ds/menuhax_manager/themepayload/'.
Install failed: 0x00000002
An error occured. If this is an actual issue not related to user failure, please report this to here if it persists(or comment on an already existing issue if needed), with a screenshot: https://github.com/yellows8/3ds_homemenuhax/issues
Press the START button to exit.

**Comment by yellows8** [comment]
Outdated release archive ...................................
