### ISSUE TITLE
15GB of files created on 4GB microSD

### ISSUE THREAD

**Issue by ghost** [yellows8/3ds_homemenuhax#141]
I finally got menuhax installed; I ran it once on launch, but now every subsequent time I try to use it, either it doesn't load at all, or the system says it screwed up. It didn't brick; I can still use it as a device, but theme management data can't be created, likely because of 15GB+ of data created in my extdata.

These 15GB+ of data are in the forms of system files and whatnot named things like, "ｰ0ﾐ痼・・0". One extdata folder is blatantly seen as corrupted by Windows. The extdata folders in quesiton are:
- 000002cd
- 00000210
- 00001794

00001794 and 000002cd is inaccessible. There was a 0000008f, but that was deleted by me. It also contained corrupted files. The other files do not let me delete them, because "the file name is too long".

**Comment by ghost** [comment]
The other extdata folders are perfectly fine.

Ah, and I should mention that browserhax cannot load HBC; it gets stuck on Orange.

Trying to delete all of the extdata nets me Windows error 0x80004005: Unspecified error.

Ah, I deeply apologize. I was wrong. It's 55.1GB. Not 15ish.

extdata DIR28 doesn't let me explicitly delete it; it only makes its files 0 bytes. Other DIRs can be deleted.

I can't delete the files from the command line.

Windows doesn't think that 55.1GB actually weight as anything, and so I still have 680MB on my SD.

**Comment by yellows8** [comment]
I guess you'll have to format your SD FS(backing up whatever you can first of course). Don't know what could cause that other than FS corruption which started earlier that you didn't notice until now.

**Comment by ghost** [comment]
Eh, I guess that works. Mostly I'm just submitting it as an issue for future reference.
Now that I'm backing stuff up, I'm also noticing that it's only the files (including the hax itself) that menuhax modified that messed up.

**Comment by ghost** [comment]
It's FAT32, correct?

**Comment by yellows8** [comment]
Yes.
