### ISSUE TITLE
Can i use this hax for downgrading with harmod?

### ISSUE THREAD

**Issue by Luis0MLG** [yellows8/3ds_homemenuhax#142]
Before creating an issue, please make sure that you:
- Properly extracted the _latest_ release-archive to your SD card. https://github.com/yellows8/3ds_homemenuhax/releases
- Read the entire README.

Note that HTTPC error 0xd8a0a046(and perhaps others) are caused by no usable network connection being available.

**Comment by Luis0MLG** [comment]
Any one knows?

**Comment by yellows8** [comment]
This is not the place to ask about downgrading.
