### ISSUE TITLE
Menuhax Error:0x0000002

### ISSUE THREAD

**Issue by SuperWuX** [yellows8/3ds_homemenuhax#143]
So I'm trying to open homebrew via menuhax
And fortunately I am able to access homebrew via browser had, but its pesky to scan the qr code and wait. That's why I go for menuhax, but when I installed it, it gave me an error, with the code 0x00000002.
Any help?

**Comment by yellows8** [comment]
That error alone isn't helpful......

**Comment by SuperWuX** [comment]
Then what am I to do?

**Comment by ghost** [comment]
Leave a dump of the full error, preferably with your system version and the version of menuhax you're using.

**Comment by yellows8** [comment]
https://github.com/yellows8/3ds_homemenuhax/commit/e4ddb94899524b4cf8afd58d549e02efef972ab6#diff-0b6c1416b1293274c4e2d11fb49e1795R7

**Comment by Halios13** [comment]
I get this same error code:

installing shufflehax...
Enabling shuffle themecache...
Reading SaveData.dat...
Writing updated SaveData.dat...
Installing to the SD theme-cache...
Failed to get the filesize of the body-filepath:sdmc:/3ds/menuhax_manager/finaloutput/shufflepayload/menuhax_USA25600_new3ds.lz
Verify that you have a menuhax build for your system on SD card: make sure that the release archive you're using actually includes builds for your system-version.
Also verify that the following directory containing .lz files actually exists on your SD card: '/3ds/menuhax_manager/themepayload/'.
Install failed: 0x00000002

Is this what you're getting as well?
Am I missing a step or files that should have been in the starter?

**Comment by yellows8** [comment]
@Halios13 Old menuhax. "or files that should have been in the starter?" <- When did you download starter.zip?

**Comment by SuperWuX** [comment]
Yep, i'm getting the same message as Halios.
And the rest of the message said to ask help on this sight and what not.

**Comment by hacksign27** [comment]
@yellows8 I've succesfully completed the entire guide twice (about 3 months ago) on my new 3DS XL, and my old 3DS xl.

I am trying to do it for my brothers now and 2 of them have NEW 3DS xl and one of them has the original 3DS (not XL).

It worked no problem with the old 3DS, getting the same error as Halios13 on the 2 NEW 3DS xl.

I downloaded the starter.zip today.

Just thought I'd relay that information to help you with troubleshooting. 
Looks like the latest update of  starter.zip file might be missing some files specific to the New 3DS XL

**Comment by yellows8** [comment]
You probably didn't extract to SD properly then.

**Comment by hacksign27** [comment]
@yellows8 Thanks, I somehow missed your post with the latest release of menuhax.

Sorry!

**Comment by Halios13** [comment]
I downloaded the starter.zip last night and I did extract it wrong the first time (couldn't even get into homebrew at all because of that), but I got this error after doing it correctly.

**Comment by yellows8** [comment]
Make sure the icon displays v3.0.....
