### ISSUE TITLE
Logging initialization failure not handled properly.

### ISSUE THREAD

**Issue by ghost** [yellows8/3ds_homemenuhax#145]
Hello! I'm quite sorry if someone has already said this but every time I try to run the menuhax-manager to change the splash I always get this error and I have to hard reset my system.

Failed to initialize logging: 0x00000002.
menuhax_manager v3.0 by yellow8.
Deleting SD data from old menuhax_manager versions.
, etc...
Opening extdata archives...
Finished opening extdata.

**Comment by yellows8** [comment]
Looks like menuhax_manager doesn't handle logging-init failure properly...

Are you certain your SD switch isn't set to write-protect?("/3ds/menuhax_manager/" exists?)

**Comment by ghost** [comment]
Oh. This might actually be a fault on my side then. Does the menuhax-manager folder have to be in the 3ds folder? 'Cause I moved it to neaten things up.

**Comment by yellows8** [comment]
"Does the menuhax-manager folder have to be in the 3ds folder?" Yes.

**Comment by ghost** [comment]
Oh, then this is totally my fault. Sorry! I'll move it now.

**Comment by ghost** [comment]
Yeah, sorry. Now it's working.

**Comment by yellows8** [comment]
https://github.com/yellows8/3ds_homemenuhax/commit/a6b44e1c75c844dfdf69ea85a2e1c63f26ce3e6b

**Comment by fennectech** [comment]
My sdcard is NOT write protected

**Comment by fennectech** [comment]
can i create /3ds/menuhax_manager or does the menuhax manager have to be IN that folder

**Comment by yellows8** [comment]
You can do the former if you _really_ _don't_ want the latter.

**Comment by fennectech** [comment]
i like to keep my hax installers in a single folder

**Comment by fennectech** [comment]
is there any way to use custom themes with menuhax amnagere?   or does it just simply not work at all

**Comment by yellows8** [comment]
README
