### ISSUE TITLE
Errors 0xFFFFFFFE and 0x00000002 OLD 3DS and XL

### ISSUE THREAD

**Issue by BlueGirl323** [yellows8/3ds_homemenuhax#146]
I apologize in advance, I have no idea what I'm doing wrong, but I can't even seem to find the error log on the SD cards at the location indicated here before posting. I'm hoping someone may be able to tell me what I'm doing wrong!
I believe I may have screwed up by installing an old version of MenuHax on one 3DS, and the other I'm not sure what the issue is.
The first is an original 3DS, not XL, USA ver 11.0.0-33 
It WAS receiving the 0xfffffffe error code, and I had read another post and it sounded like I had the incorrect files installed, I grabbed 3.0 from -> https://github.com/yellows8/3ds_homemenuhax/releases/tag/v3.0 
Renamed ext.data, loaded into themes, and then installed MenuHax no problem.
(I was having issues but got it to work as I'm writing this post, so I wanted to include it for anyone else having this issue)
The second is the OLD 3DS XL, USA ver 11.0.0-33
It's receiving the 0x00000002 error. I followed the same steps I did above but am still getting an error, I believe I have the correct payloads, and if it makes any difference my original entry point is through SmileHax. 
Again, I apologize for not including the log, the only log I can find just has the menu text from in-app.

**Comment by yellows8** [comment]
"Again, I apologize for not including the log, the only log I can find just has the menu text from in-app." That's the file you're supposed to include.

**Comment by BlueGirl323** [comment]
There was nothing else written in it though? Lol

**Comment by yellows8** [comment]
Just include it .....

**Comment by BlueGirl323** [comment]
I feel really stupid but- I don't even see the same files on my second 3DS, would you mind pointing out which one specifically? I think I may have screwed up on my second one :L 
![f](https://cloud.githubusercontent.com/assets/20730080/17261353/4b57ea96-55a3-11e6-855f-4778f5fb9df7.png)

**Comment by yellows8** [comment]
That's not v3.0.

**Comment by BlueGirl323** [comment]
Ooookay then, seriously so sorry for my stupid questions. I just deleted everything menuhax related, and re-added the files from the v3.0 and it finally installed successfully. I should have just tried that instead of bothering you! 
I think what happened is when I dragged v3.0 over originally, I released inside the first 3DS folder by mistake. :/ 
I'm so sorry for my stupidity >_<

**Comment by yellows8** [comment]
Well if everything is installed fine now close the issue.
