### ISSUE TITLE
Error when installing menuhax.

### ISSUE THREAD

**Issue by Airpoizon** [yellows8/3ds_homemenuhax#148]
So I when I went and installed the homebrew starter kit, I tried to load menuhax, but it gave me the 0xfffffffe error. So after that didn't work, I went ahead and installed the menuhax V3 directly from this site, yet that still didn't work. Here are what the files look like on my SD card:

![screenshot 2016-07-29 at 4 29 17 pm](https://cloud.githubusercontent.com/assets/20731254/17262666/b93339ec-55aa-11e6-8c9a-9773c81d345e.png)

I appreciate the help.

**Comment by yellows8** [comment]
#131
