### ISSUE TITLE
Menuhax Not Working

### ISSUE THREAD

**Issue by Anonymous42456** [yellows8/3ds_homemenuhax#149]
I get this error when I open Menuhax.

menuhax_manager v3.0 by yellows8.
Deleting SD data from old menuhax_manager versions, etc...
Opening extdata archives...
Finished opening extdata.

Downloading config via HTTPC...
Failed to initialize HTTPC: 0xd8e06406.
Config download failed(0xd8e06406), trying to load it from SD...
Failed to load config from SD: 0x00000002.
Failed to load config: 0x00000002.

An error occured. If this is an actual issue not related to user failure, please report this to here if it persists(or comment on an already existing issue if needed), with the file from SD '/3ds/menuhax_manager/menuhax_manager.log': https://github.com/yellows8/3ds_homemenuhax/issues
Press the START button to exit.

**Comment by yellows8** [comment]
#132
