### ISSUE TITLE
Cannot download config

### ISSUE THREAD

**Issue by samsimpson1** [yellows8/3ds_homemenuhax#152]
Unlike in issue #132 I am not getting an error. It is hanging on "Downloading config via HTTPC".

I cannot access yls8.mtheall.com at all from my PC:

```
{ ~ }  » ping yls8.mtheall.com

Pinging mtheall.com [107.211.140.65] with 32 bytes of data:
Request timed out.
Request timed out.
Request timed out.
Request timed out.

Ping statistics for 107.211.140.65:
    Packets: Sent = 4, Received = 0, Lost = 4 (100% loss),
```

![Chrome](https://tophattedcat.co.uk/files/chrome_2016-07-31_22-53-24.png)

And I also cannot access it from my mobile phone via 4G.

**Comment by kanekeller** [comment]
I'm having the exact same issue on both of my consoles (o3ds, n3dsxl).

**Comment by shilofax** [comment]
Having the same issue. (2ds)

**Comment by yellows8** [comment]
yellows8/browserhax_site#7

**Comment by shilofax** [comment]
Thank you for the update, I'll try again in a few hours.
