### ISSUE TITLE
Themes

### ISSUE THREAD

**Issue by Sompursone** [yellows8/3ds_homemenuhax#159]
Just wondering before I try it, so I don't screw things up, can you change the theme using the custom theme manager within the Homebrew launcher without messing up menuhax?

**Comment by yellows8** [comment]
"custom theme manager" ?

**Comment by ghost** [comment]
I think he means the CHHT or whatever it's called. The one bundled into the Starter Kit.
And no, that doesn't screw anything up, so long as you're using a downloaded theme and not a personally made one. If you're doing the latter, make an SD backup. Just in case. It depends on what you mess up.

For future reference, menuhax has nothing to do with these custom theme installers, so post your issue on the respective github page.

**Comment by yellows8** [comment]
FWIW this is documented in the _README_ for when sdiconhax is installed.
