### ISSUE TITLE
Crash when select settings app while using custom theme

### ISSUE THREAD

**Issue by kot2002** [yellows8/3ds_homemenuhax#16]
FIRM : 9.0.0-20 E

When I select settings app on the home menu, 3ds goes to hb launcher If body_LZ.bin used in building themepayload is larger than about 1MB.

Decompressed body_LZ.bin size : 918KB - no problem, 1171KB - entering hb launcher

It may not be associated with their size, not so sure.

**Comment by yellows8** [comment]
What theme?

EDIT: And what's the final themehax .lz filesize?

**Comment by kot2002** [comment]
I tested Zelda and Super Smash Bros themes (EUR official ones)
LoZ - Dire Moon : works
SSB Theme 2 : enters to hb launcher *
SSB Theme 3 : enters to hb launcher *

**Comment by yellows8** [comment]
What's the final themehax .lz filesizes for the ones which cause crashes?

**Comment by kot2002** [comment]
Oh I have changed comments. 
They are not crashing but makes 3ds enter hb launcher.

**Comment by yellows8** [comment]
So you aren't pressing the hax trigger button? What build params did you use?

**Comment by kot2002** [comment]
I used padcheck=0x0 to autoboot, sorry :(
When I change to 0x200, error message appears when I select on the settings app.

**Comment by yellows8** [comment]
"error message" ?

**Comment by kot2002** [comment]
final LZ size : 

1,376,254 (LoZ - Dire Moon) - not acting weird
1,376,255 (SMB2) - weird..
1,376,249 (NES Fire-Breathing Bowser, decomped body_LZ : 1,207,072B ) - weird too

1,376,252 (ACNL Timmy & Tommy Nook, decomped body_LZ : 941,216B ) - not weird

error message : 3DS system message (An error has occurred. Please save your data in any software......)

**Comment by yellows8** [comment]
Holding down the trigger button on v10.1 when launching System Settings doesn't trigger the hax here, without the THEMEDATA option. You meant "System Settings", right?

**Comment by yellows8** [comment]
Can't really debug when I don't have those particular themes either(don't have any non-free official ones).

**Comment by yellows8** [comment]
This was fixed in my local commit mentioned in #12, tested by @Myriachan with two of the themes you mentioned.
