### ISSUE TITLE
Failed to Initialize logging: 0x00000002 N3DS 11.0

### ISSUE THREAD

**Issue by rpalmon** [yellows8/3ds_homemenuhax#163]
Hello I keep getting this error when I open menuhax_manager3.0

Sorry that it is upside down.

![img_0034](https://cloud.githubusercontent.com/assets/19790545/17466740/65614d3c-5cca-11e6-9874-790958820883.JPG)

**Comment by yellows8** [comment]
#145

**Comment by Laslow** [comment]
![20160809_163811](https://cloud.githubusercontent.com/assets/20927420/17516620/9a68d9c8-5e50-11e6-837f-4f0314148d7a.jpg)

it is not working for me
![20160809_163811](https://cloud.githubusercontent.com/assets/20927420/17516632/ae8b730c-5e50-11e6-90df-834453442a7f.jpg)

**Comment by yellows8** [comment]
That is _not_ v3.0.

**Comment by fennectech** [comment]
Seeing this issue with v3.0 downloaded today O3ds 11.0.0

**Comment by yellows8** [comment]
https://github.com/yellows8/3ds_homemenuhax/issues/163#issuecomment-238230979
