### ISSUE TITLE
Present icons in all my menu

### ISSUE THREAD

**Issue by Poncus** [yellows8/3ds_homemenuhax#164]
I've been having problems with my legal downloaded apps since i installed the menuhax, the problem is that no matter how many times i open the "present" icon in my apps it stills resets everytime i reset or turn on my console, its very annoying because i have 40+ of them and they all get out of the folders.
I guess it haves something to do with the exdata folder, is there something i can do about it? i really hate that bug

**Comment by yellows8** [comment]
#154
