### ISSUE TITLE
Black screen of the Death after updating.

### ISSUE THREAD

**Issue by HanaMobiyuki** [yellows8/3ds_homemenuhax#166]
Hello, I have a big problem since I updated the menuhax from 2.2 to 3.0 on my New3DS on the last firmware version 11.0.0.33E
I don't know if it's the menuhax which have cause that issue or several other things but I need your help !
After installing, i've rebooted my console and the black screen happened, i've tried the recovery mode methode but nothing happening, and remove the SD card is useless, there is any other method to cleanup the theme to default or to boot on setup?

**Comment by yellows8** [comment]
"updated the menuhax from 2.2 to 3.0" "11.0.0.33E" That makes no sense, v2.2 didn't support v11.0.

Are you certain you had the SD card properly removed before booting the system?

**Comment by HanaMobiyuki** [comment]
Yes indeed i'm a little bit confused, infact i've just installed the menuhax 3.0 on the 11.0.0.33E, but after that, black screen on reboot and no way to boot on recovery mode.
But now my console is soft bricked :( And i'm really confused about that.
(Edit) And yes, i've properly removed the SD card before booting the sys.

**Comment by yellows8** [comment]
Same thing with SD and gamecard removed before turning on power?

**Comment by HanaMobiyuki** [comment]
Yes, but only the blue light is turned on and the two screens stay black
 and I need to press the power button 5 seconds and wait 5 other seconds before the power turn off

**Comment by yellows8** [comment]
" or several other things" ?

**Comment by HanaMobiyuki** [comment]
Infact i've tried to install the Ninjhax on 11.0.0.33 before installing the menuhax, but it did not work, so i've installed the menuhax by the browserhax, i don't know if that may have cause my issue but for now i'm stucked with that problem.

**Comment by yellows8** [comment]
Try holding down L+R+B+DPad_Down while booting the system, select whatever the OK option is once the dialog displays.

**Comment by HanaMobiyuki** [comment]
I've tried, but nothing happened, only the black screen.

**Comment by yellows8** [comment]
Install log?(And did you do anything else while the system was on before installing menuhax?)

EDIT: "and no way to boot on recovery mode." So it failed to boot into recovery-mode?

EDIT2: "After installing, i've rebooted my console and the black screen happened, " How exactly did you reboot?

**Comment by HanaMobiyuki** [comment]
Can't find the logs (I've cleaned up the SD card after several attempt of boot to see if that's come from a missing of space), and no I've didn't do anything else while the system was on.

**Comment by yellows8** [comment]
"EDIT ..."

**Comment by HanaMobiyuki** [comment]
I can't launch the recovery mode, and the console don't boot.
I've rebooted the console by the homebrew reboot option.

**Comment by yellows8** [comment]
That's _far_ too early in boot for menuhax or even browserhax _themselves_ to brick anything - some sort of hardware failure would make more sense.

If temporarily removing the battery doesn't help, the only option for fixing it is to send it to Nintendo.

**Comment by HanaMobiyuki** [comment]
Okay, thanks anyway for the support, and thank you for addressing my problem ^^

**Comment by Pryoness** [comment]
I seem to have the same problem as Mobirelanders, I was downgrading from 10.3 to 9.2 and after I finished the downgrade my system didn't reboot into 9.2 and instead I had a black screen. After a bit I powered down and now my 3DS is acting exactly like his. I think I hard bricked it because I cant launch recovery mode either.

**Comment by yellows8** [comment]
"downgrading ... black screen" This has *nothing* to do with menuhax.

**Comment by Pryoness** [comment]
Yea, sorry for commenting here I know it isn't the right place but he had a similar problem I thought you might be able to assist me. Or even just help me figure out what I did wrong.

**Comment by yellows8** [comment]
Go elsewhere for downgrade-fail help.

**Comment by Pryoness** [comment]
Suggestions?
