### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Flow3rGuy** [yellows8/3ds_homemenuhax#167]
menuhax_manager v3.0byellows8.
Deleting SD data from old menuhax_manager versions
.etc...
Opening extdata archives...
Failed to open theme extdata with extdataID=0×0000
02cc,retval: 0×c8804464
Exit this app, them goto Home Mene theme-settings
so that Home Menu can create the theme extdata.

An error occured.It this is an actual 
issue not related to user failure, Please report this to here if it persists (or comment on an already existing issue if needed), with the file.from SD  /3ds/menuom/yellows8/3ds_homemenuhax/issues
press the START button to exit.

Resolution you want.

**Comment by yellows8** [comment]
...................................................

**Comment by Flow3rGuy** [comment]
How can I resolve it?

**Comment by TuxSH** [comment]
@ishida0025

> Exit this app, them goto Home Mene theme-settings
> so that Home Menu can create the theme extdata.

**Comment by Flow3rGuy** [comment]
@TuxSH Thank very much!
I'm sorry if you can not do anything.
