### ISSUE TITLE
Installing/changing settings offline

### ISSUE THREAD

**Issue by thiagokokada** [yellows8/3ds_homemenuhax#17]
This issue is actually to proposals related to `themehax_installer`:
- The menu where you can choose if you want to install, configure or exit `themehax_installer` should appear before checking of internet availability. Because you don't need internet to just change if you want autobooting or not, or if you want to change the override button. Nowadays if you do want to change those options you have to have internet even when you don't need (or you get a HTTPD error).
- When `/themehaxinstaller_otherapp_payload.bin` is present the installer shouldn't check for internet either, so we can do a completely offline install if this is needed by some reason.

**Comment by yellows8** [comment]
I'm not sure what "check for internet" you're on about. The HTTP requests are only done during the install when it can't find the SD payload.

Are you trying to say httpcInit is returning an error when Internet isn't available?

**Comment by thiagokokada** [comment]
Yeah, that's it. Since this gives an error I can't do too much inside the application. The only option is exit and go back to Homebrew Launcher.

**Comment by yellows8** [comment]
This is fixed in my local changes(moved httpcInit/httpcExit into the actual code area where it does HTTP requests).
