### ISSUE TITLE
Install failed: 0*00000002

### ISSUE THREAD

**Issue by chensiyue98** [yellows8/3ds_homemenuhax#172]
When I try to install menuhax on my new 3DS (JPN 11.0.0-33J), I always get errors. 
## All the files are the latest. Please help me.

Checking for the input payload on SD...
Requesting the actual payload URL with HTTP...
Downloading the actual payload with HTTP...
Writing the menuropbin to SD, to the following path :  sdmc:/ropbinpayload_menuhax_JPN27648_new3ds.bin.
Installing shufflehax...
Enabling shuffle themecathe...
Reading SaveData.dat...
Writing updated SaveData.dat...
Installing to the SD theme-cache...
Failed to get the filesize of the body-filepath: sdmc:/3ds/menuhax_manager/finaloutput/shufflepayload/menuhax_JPN27648_new3ds.lz
Verify that you have a menuhax build for your system on SD card: make sure that the release archive you're using actually includes builds for your system-version.
Also verify that the following directory containing .lz files actually exists on your SD card: `/3ds/menuhax_manager/themepayload/`.
Install failed: 0*00000002.

**Comment by yellows8** [comment]
old-menuhax
