### ISSUE TITLE
After installing MenuHax, all of my installed 3ds games are turned back into Present icons

### ISSUE THREAD

**Issue by ben43210** [yellows8/3ds_homemenuhax#174]
Hello,  this is isint exactly a issue that im having with installing MenuHax, but rather a issue im having after ive installed it... I can install MenuHax by deleting/renaming the home menu extdata folder and MenuHax installs correctly. However, when i restart my 3DS system and return to my Main Menu, ive found that all of my 3DS games that ive downloaded previously from the Nintendo Eshop are scattered all over my home menu and every single one is changed into the 'Present Icon' that the system shows you after downloading a new piece of software.

I have placed all of my apps back where they were before (in four created folders), however when i restart my 3DS system, all of my applications are back out of their folders and once again show the 'Present Icon'. I know this isint really a issue with menuHax, but can anyone tell me why this is happening? since im worried that im damaging my 3ds system by trying to run the homebrew launcher. I would also like to know if anyone else is experiencing the same issues and what can i do to stop this from happening?

For now, i have reverted back to a backup before any homebrew hacking was done on my 3ds. I know this can be avoided by not deleting/renaming the extdata folder, however i cannot install MenuHax without doing this!

Any help would be appreciated. Thank you :)

**Comment by yellows8** [comment]
README + #154
