### ISSUE TITLE
Won't let me download?

### ISSUE THREAD

**Issue by ghost** [yellows8/3ds_homemenuhax#175]
menuhax_manager v3.0byellows8.
Deleting SD data from old menuhax_manager versions
.etc...
Opening extdata archives...
Failed to open theme extdata with extdataID=0×0000
02cc,retval: 0×c8804464
Exit this app, them goto Home Mene theme-settings
so that Home Menu can create the theme extdata.

An error occured.It this is an actual 
issue not related to user failure, Please report this to here if it persists (or comment on an already existing issue if needed), with the file.from SD /3ds/menuom/yellows8/3ds_homemenuhax/issues
press the START button to exit.

What now? I've tried deleting "extdata" files and renaming them. I saw there was another thread with the same issue but mine didn't work with that solution. (Yes I am updated to the latest version and downloaded the latest version of home brew). Please help. (Version 11.0 on a 2ds)

**Comment by Waleed-AlSomali** [comment]
I have the same issue as asiandequan but on New3DS newest version 11.0.0.33U

**Comment by ghost** [comment]
Try pushing power and R at same time and keep holding R until system turns on, it should load to home screen
