### ISSUE TITLE
menuhax manager not working

### ISSUE THREAD

**Issue by ChampionLeake** [yellows8/3ds_homemenuhax#176]
"menuhax_manager v3.0 by yellows8.
Deleting SD data from old menuhax_manager versions, etc...
Opening extdata archives...
Finished opening extdata.

Downloading config via HTTPC...
Parsing config...
This menuhax_manager build's version doesn't match the version from config.
You likely aren't using the latest release version, outdated versions are not supported.
Failed to load config: 0xfffffffe.

An error occured. If this is an actual issue not related to user failure, please report this to here if it persists(or comment on an already existing issue if needed), with the file from SD '/3ds/menuhax_manager/menuhax_manager.log': https://github.com/yellows8/3ds_homemenuhax/issues
Press the START button to exit."

I'm having that issue. I download the manager again it still won't work. This is causing my 3ds o crash when I have my sd card inserted. When it's not inserted everything is fine. When I open the internet browser an put in my sd card to load browserhax everything is fine. I really want this issue resolved. All I wanted to do was to delete menuhax.

**Comment by SaturnSH2x2** [comment]
Same issue here, tho keep in mind that I deleted my old MenuHax folder to make room for this new one?  Is that what's causing issues?

**Comment by Wolfnut88** [comment]
I kept running into this issue too. I realized that version 3.1 came out today. I got it working by deleting the old "menuhax_manager" folder and dropping in the new one and it worked just fine. Hope it helps.

**Comment by yellows8** [comment]
......................................................................
"You likely aren't using the latest release version, outdated versions are not supported."

**Comment by ChampionLeake** [comment]
Can you please be more specific instead of quoting? At least ask some questions like "What's your firmware" or "Do you use CFW"

**Comment by Wolfnut88** [comment]
@ChampionLeake
He means you need to download and update your version. I did it by manually deleting the old menu hax folder and then adding the new folder from the 3.1 update. You're firmware version shouldn't matter because the error is happening due to an outdated version of "menuhax_manager."

**Comment by yellows8** [comment]
Why can't you understand the _displayed error message_?

**Comment by Marrrcg** [comment]
hey does anyone have the link to downloading version 3.1 of the menuhax_manager? i cant find anywhere to downloaded the latest version

**Comment by Wolfnut88** [comment]
@Marrrcg 
You can follow the posts through yellows8 updates and get to the latest version. I am still reading up on the rules so I don't know if I can post links, mods please delete if I am no allowed. Here is the link to his page with the download: https://github.com/yellows8/3ds_homemenuhax/releases

If the link doesn't work here is how to get to the DL manually; 
1. click on "yellows8" name above
2. click on "3ds_homemenuhax"
3. you should see four floating links labeled "commits, branch, releases, contributors" click "releases"
4. scroll down to the downloads section and click "menuhax_v3.1.zip"
5. profit

**Comment by ChampionLeake** [comment]
There wasn't a 3.1 release yesterday. But I have downloaded it. Fixed the issues. Everything is clean.

**Comment by yellows8** [comment]
"There wasn't a 3.1 release yesterday. " There was, otherwise that error wouldn't trigger...

**Comment by Clement95** [comment]
Hello, I have the same problem except that the version of menuhax_manager is 3.1

**Comment by Clement95** [comment]
Hello, I have the same problem except that the version of menuhax_manager is 3.1
