### ISSUE TITLE
Failed to load config: 0fffffffe

### ISSUE THREAD

**Issue by Ocampo3** [yellows8/3ds_homemenuhax#179]
Eveytime I try to download menuhax_manager v3.0 it gives me this error. Please help.

**Comment by zickZack01** [comment]
Same Issue here :/

**Comment by Ocampo3** [comment]
What version are you running on your 3ds?

**Comment by liujian1201** [comment]
VERSION: 11.0.0-33J

**Comment by yellows8** [comment]
#176
