### ISSUE TITLE
I have a problem! "This menuhax_manager build's version doesn't match the version from the config."

### ISSUE THREAD

**Issue by josepanello** [yellows8/3ds_homemenuhax#180]
Hello,
It is that, when trying to open it, puts me this:

menuhax_manager v3.0 by yellows8.
Deleting SD data from old menuhax_manager versions, etc...
Opening extdata archives...
Downloading config via HTTPC...
Parsing config...
This menuhax_manager build's version doesn't match the version from the config.
You likely aren't using the latest release version outdated versions are not supported.
failed to load config: 0xfffffffe.
An error ocurred. If this is an actual issue not releated to user failure, please report this to here if it persists (or comment on already existing issue if needed), with the file from SD /3ds/menuhax_manager/menuhax_manager. log: https://github.com/yellows8/3ds_homemenuhax/ issues
Press the start button to exit.

**Comment by yellows8** [comment]
#176

**Comment by josepanello** [comment]
Thanks! @yellows8
