### ISSUE TITLE
Site down

### ISSUE THREAD

**Issue by Daryth** [yellows8/3ds_homemenuhax#182]
Please delete.

**Comment by ElgrigoJR** [comment]
Got the same issue.
Had the QR code saved but can't launch homebrew

**Comment by ElgrigoJR** [comment]
Here dunno if it helps!
![3dsbrowserhax_auto_qrcode](https://cloud.githubusercontent.com/assets/21180073/17865836/067228a4-689c-11e6-8ecd-b8fdf938fb78.png)
