### ISSUE TITLE
menuhax_manager v3.0 download failure

### ISSUE THREAD

**Issue by yumastreet** [yellows8/3ds_homemenuhax#183]
This  is the error I keep getting when I try to do the part with the Menuhax_manager plz helper

menuhax_manager v3.0 by yellows8.
Deleting SD data from old menuhax_manager versions, etc...
Opening extdata archives...
Finished opening extdata.

Downloading config via HTTPC...
Parsing config...
This menuhax_manager build's version doesn't match the version from config.
You likely aren't using the latest release version, outdated versions are not supported.
Failed to load config: 0xfffffffe.

An error occured. If this is an actual issue not related to user failure, please report this to here if it persists(or comment on an already existing issue if needed), with the file from SD '/3ds/menuhax_manager/menuhax_manager.log': https://github.com/yellows8/3ds_homemenuhax/issues
Press the START button to exit.

**Comment by yellows8** [comment]
https://github.com/yellows8/3ds_homemenuhax/releases

**Comment by yumastreet** [comment]
So i download the 3.1 drag drop and continue as normal or?
