### ISSUE TITLE
3.1v help. 

### ISSUE THREAD

**Issue by yumastreet** [yellows8/3ds_homemenuhax#184]
So you gave me the link, do I drag and drop that  on to my SD and replace  it with whats on there. Do  I have to download the sources too?

**Comment by Waleed-AlSomali** [comment]
I can't open the Read me. Can Someone please help me how to this process step by step ?
Thank you for your time.

**Comment by TheBunnyCoder** [comment]
1. go to https://github.com/yellows8/3ds_homemenuhax
2. go to the bottom of the page where it says 'readme'
3. read it.
