### ISSUE TITLE
issue 0x00000001

### ISSUE THREAD

**Issue by aliarisu** [yellows8/3ds_homemenuhax#188]
I load the last menuhax_manager 3.1 and it doesn´t work me. I have the 10.7.0-32e and homebrew launcher,but thisissue ALWAYS appear me when i clicked install. And i don¨t know how to solve it :( I searched on this page and anyone post this issue. PLEASE HELP ME

install failled : 0x00000001.  An error ocured. If this is an actual issue not related to user failure, please report this to here if it persists (or comment on an already existing issue if needed), with the fille from SD ¨menuhax_manager.log¨ (normally located at /3ds/menuhax_manager/. unless the app is running from elsewhere): http://github.com/yellows8/3ds_homemenuhax/issuess Press the start button to exit.

**Comment by yellows8** [comment]
"with the file from SD ..."

**Comment by aliarisu** [comment]
Could you be more specific? I don't understand it :') sorry, i'm a little noob in this

**Comment by aliarisu** [comment]
Please. I can't deal,with it XD  i put your last folder on de /3ds/. And then opened it with browserhax. And when I put Install, that message appear.7u7 i can't do nothing without menuhax now

But thank you for all your great work yellows8, you deserve it
