### ISSUE TITLE
issue 0x00000001 with log

### ISSUE THREAD

**Issue by aliarisu** [yellows8/3ds_homemenuhax#189]
install failled : 0x00000001. An error ocured. If this is an actual issue not related to user failure, please report this to here if it persists (or comment on an already existing issue if needed), with the fille from SD ¨menuhax_manager.log¨ (normally located at /3ds/menuhax_manager/. unless the app is running from elsewhere): http://github.com/yellows8/3ds_homemenuhax/issuess Press the start button to exit.
this is the issue
[https://drive.google.com/open?id=0B_TT0HnTeZlJbndFUnh6VHBsQ1k](url)
sorry

**Comment by yellows8** [comment]
Try installing again and upload the log.

**Comment by aliarisu** [comment]
i upload your three folders in the root of the SD but it still liki this

**Comment by aliarisu** [comment]
hey yellows8, i already upload the log. Look at the last link ;)   And sorry for my English and questions, I¨m SPanish and noob here

**Comment by yellows8** [comment]
0-byte log .........

**Comment by aliarisu** [comment]
sorry,you can delete this post and answer me in the new one,which has the log
