### ISSUE TITLE
issue 0x00000001

### ISSUE THREAD

**Issue by aliarisu** [yellows8/3ds_homemenuhax#190]
Sorry for my third post :S but I need your help and I didn´t understand you before :´)
I load again your fille and nothing. Here i post the final log.

[https://drive.google.com/open?id=0B_TT0HnTeZlJbndFUnh6VHBsQ1k](url)
sorry,but I´m noob in this so I understand a little XD if you could guide me step a step it would be better. By i understan that you have lot of work, so sorry for loosing your time with me :)

**Comment by yellows8** [comment]
Read the displayed text .....................

**Comment by aliarisu** [comment]
sorry :´( I read the displayed of my issue,yes? but i dont know what to do. I post the log here,no? what more?

**Comment by aliarisu** [comment]
@yellows8 please help me. Without menuhax I can't instal nothing withouth it :(                   I didn't find how to fix it. So I need your help cause I know you will help me :)

**Comment by yellows8** [comment]
https://github.com/yellows8/3ds_homemenuhax/issues/190#issuecomment-242515501

**Comment by aliarisu** [comment]
I don.t understan the displayed text of my issue. I read thousand times but i can:t fix it. I tried also on my two  consoles but the issus still there :( @yellows8

**Comment by yellows8** [comment]
Then you don't really understand English either.
