### ISSUE TITLE
Menuhax manager: exclude reserved "PAD Values" for starting menuhax.

### ISSUE THREAD

**Issue by My1** [yellows8/3ds_homemenuhax#191]
I tried up setting up Menuhax with L+R+X as trigger and then I found out something intresting:
http://en-americas-support.nintendo.com/app/answers/detail/a_id/269/~/how-to-calibrate-the-touch-screen
L+R+X seems to start an emergency calibration mode (seriously great Idea because the people at nintendo thought it would be nice removing the option of using the dpad and buttons for the settings from DSi onward)
I dont know whether or not others like these exist)
but this may be confusing so it might be help users to just say that this combination doesnt work because they might hit the realization at a time where a different entrypoint to the manager isnt available (e.g. no internet when using browserhax as first entrypoint

**Comment by yellows8** [comment]
Implemented with a local commit(includes other keycombos as well).

**Comment by My1** [comment]
ehm stupid question what are those other key combos, they might actually be quite helpful to know.

**Comment by yellows8** [comment]
https://gist.github.com/yellows8/0b99f8bb5ea4fdba3687de4dd2d63f4a
