### ISSUE TITLE
Im following the instructions via the app but getting this message :(

### ISSUE THREAD

**Issue by temaana** [yellows8/3ds_homemenuhax#194]
Help me! I'm new to this and not sure what I'm doing wrong  :( 
![image1](https://cloud.githubusercontent.com/assets/21969408/18224324/bd3c187a-7214-11e6-8745-bec3f82dfee3.JPG)

**Comment by yellows8** [comment]
https://github.com/yellows8/3ds_homemenuhax/releases/latest

"Im following the instructions via the app" Nope....
