### ISSUE TITLE
Problem 0x0000001

### ISSUE THREAD

**Issue by rodrigo2804** [yellows8/3ds_homemenuhax#196]
I read the comments but i not understand ,  my question is i need a  new archive or i need the archive READ ME.

What its your best advice? Sorry :(

**Comment by passievrucht** [comment]
I always get that issue too. I follow the instructions of codeumbreon.

**Comment by passievrucht** [comment]
After you click install press first A then twice B and it will work

**Comment by Oshutoru** [comment]
i have the same problem, what can i do?, help me plz :(

**Comment by rodrigo2804** [comment]
Oshotoru Después de hacer clic en instalar prensa Una primera luego dos veces B y funcionará
