### ISSUE TITLE
homebrew launcher(override the detected system version)

### ISSUE THREAD

**Issue by jasontwk85** [yellows8/3ds_homemenuhax#197]
Hi..im new..
At homebrew launcher step.. got writen if (override the detected system version).. choose decline..
But i accidently press 'yes'.. and now i fail to boot to original home menu. 
As soon i reach this step and error,i stop all my process.
Should i continue or fix it back 1st or what should i do?

Thanks.
And sorry for inconvenience cause.

**Comment by yellows8** [comment]
https://github.com/yellows8/3ds_homemenuhax#summary

**Comment by jasontwk85** [comment]
Thanks for reply..the summary i also got read.. but not so sure (sorry my english bad too)
Should i just remove the sd card then redo the process again as nothing happen?

Thanks.
And sorry for inconvenience cause..

**Comment by yellows8** [comment]
Yes.

EDIT: You probably have to manually delete the extdata though.

**Comment by jasontwk85** [comment]
Ok.. thank you very much.. will try to redo it again..

**Comment by jasontwk85** [comment]
Ok.. can teach me how manually delete extdata? 

Thanks.

**Comment by jasontwk85** [comment]
The extdata on sdcard? Or i just redo the step from beginning? (Delete sd card then put startup folder to sd card and do again as nothing happen before?)

Thanks.
And sorry for inconvenience cause.

**Comment by yellows8** [comment]
Maybe you could boot without SD inserted, then insert once the web-browser boots.

**Comment by jasontwk85** [comment]
You mean boot without sd card inserted.then insert and do the web browser step again?

**Comment by yellows8** [comment]
Yes. Do NOT insert SD until the browser boots.

**Comment by jasontwk85** [comment]
Ok.. thank you very much👍

**Comment by jasontwk85** [comment]
Sorry again,
I just try again.. it is normal at (homebrew launcher (browser)) step no.16.. after press start then press A to reboot.. it back to homebrew launcher?

**Comment by jasontwk85** [comment]
Or do u mean i should continue my step on 9.2 downgrade..
Sect.1 done then proceed to sect. 2.. boot without sd card?

Sorry..my bad english and bad understanding.

Thanks

**Comment by yellows8** [comment]
Do not ask about downgrading here.
