### ISSUE TITLE
Failed to download config

### ISSUE THREAD

**Issue by Shadowrend** [yellows8/3ds_homemenuhax#198]
Menuhax_manager v3.1
Deleting Sd data from old menuhax_manager veraions etc.
Opening extdata arcives...
Finished opening extdata.
Downloading config via HTTPC...
Config download failed (0xd8a0a046), trying to load it from SD...
Failed to download config from SD: 0x00000002.
Failed to download config:0x00000002.
Please help me

**Comment by Shadowrend** [comment]
I have firmware 10.3 and i want to use my gateway. Since the site of Gateway says it supports up to firmware 10.7, does that mean I dont have to downgrade my device? Please help me. I need help.

**Comment by yellows8** [comment]
Network fail, retry. Do not ask about downgrading here.

**Comment by neocrypton** [comment]
i use menuhax_manager v3.1 and i get some errors..

my 2DS try to download the config via HTTPC then i get following erros:

Config download failed(0xd8a0a049), trying to load it from SD...
Failed to load config from SD: 0x00000002.
Failed to load config: 0x00000002.

anyone can help?

**Comment by yellows8** [comment]
#218
