### ISSUE TITLE
homebrew launcher 9.0.0-9.2.0

### ISSUE THREAD

**Issue by jasontwk85** [yellows8/3ds_homemenuhax#199]
Hi.. and sorry again..
After i do all process.. my device is 9.7.0-25j.. become 9.1.0-20j...
I dunno how to do.. and i redo follow the guide (9.0.0 -9.2.0).. but in the end my device setting still not shown 9.2.0.. 

At "Decrypt9WIP" step.. just copy "Decrypt9WIP" folder from  only to /3ds/ only.. then put sd card to device and open (from complete power off) or standby mode?cos every time before i remove sd card i complete power off my device..

Thanks

**Comment by cheatfreak47** [comment]
Japanese 3DSs I think never got 9.2, so the guide uses 9.1 instead.
Once downgraded to 9.1, proceed as normal with plailect's guide.

If I am mistaken someone surely will correct me.

However, this is absolutely not got _anything_ to do with HomeMenuHax. 
Don't post QA sorts of questions on random 3DS related trackers. It's impolite.

Instead, please direct all QA sorts of questions to GBAtemp or Reddit's /r/3dshacks in the stickied QA thread.

This should probably be closed.

**Comment by yellows8** [comment]
"Japanese 3DSs I think never got 9.2" <- Wrong. v9.1 was JPN-only though.

Closing this due to " this is absolutely not got anything to do with HomeMenuHax. "

**Comment by jasontwk85** [comment]
Sorry..everyone.. 😔 i thought under 'homebrew launcher' is under this post..
I dunno is another step and dunno is not got anything to do with homemenuhax..

Really sorry.. 
My mistake..

Thanks,
And sorry for inconvenience cause..
