### ISSUE TITLE
Issue booting into Homebrew Launcher from New Super Mario Bros 2

### ISSUE THREAD

**Issue by xxbilxx** [yellows8/3ds_homemenuhax#20]
I have been using the workaround provided by smealum (until 2.5 comes out) to boot into the Homebrew Launcher to use core1 applications. 

Whenever I press the power button while NSMB2 is running, the power-off screen comes up like normal; however, when I press the home button and hold L, my 3DS displays the normal debug code but never boots and then freezes. It freezes on what I assume is random memory locations each time. 

I am using themehax on a New 3DS. Oddly enough, I tested if this problem occurred when launching via other games, but none of my other 16 games had this issue. 

If you need more info, please reply to the issue!

**Comment by yellows8** [comment]
"It freezes on what I assume is random memory locations each time." Be more specific.

**Comment by xxbilxx** [comment]
I will not have access to my 3DS until the weekend, but the top screen displayed this text before the system locked up. It stayed locked until I hard reset it. I found the debug text from my browser history (I was curious if it was documented before).

hello 38c43300 got APT:A lock handle ? 0000000, 00cd8003, 00ce0004
