### ISSUE TITLE
Unable to boot to Home Brew Menu when holding L button

### ISSUE THREAD

**Issue by desmond1495** [yellows8/3ds_homemenuhax#200]
Version: 11.0.0-33u

I used a clean (formatted) SD card with the boot files, managed to go into Home Brew Menu and installed menuhax (stated on the screen). After i reboot, I pressed the power button and held the L button, it didnt boot back to Home Bew Menu and nothing happened. After that, i press Home Menu, the theme changes back from basic black to default theme (this happens after i installed menuhax). I followed a guide and it said not suppose to change the theme after menuhax installed.

Able to help with this issue?

**Comment by yellows8** [comment]
Enter the menuhax_manager config menu to check what the PAD config is set to?

**Comment by desmond1495** [comment]
They stated default PAD trigger is used

**Comment by yellows8** [comment]
"After i reboot, I pressed the power button and held the L button, it didnt boot back to Home Bew Menu and nothing happened. After that, i press Home Menu" Can you be more specific?("nothing happened" "press Home Menu")

**Comment by desmond1495** [comment]
I pressed the power button in order to press the L button to boot into Home Brew Menu. However, it is not booting into Home Brew Menu. Thus, I clicked Home button, which brings me back, and the theme changed back to default by itself.

Could you advise me on that?

**Comment by yellows8** [comment]
"Thus, I clicked Home button" wut

**Comment by desmond1495** [comment]
When i click the power button, it shows the option to 'Power Off' at the bottom. Since it could not boot into the Home Brew Menu with L button, I clicked the Home button instead to go back as I don't want to power it off.

**Comment by yellows8** [comment]
Can you install again + test, and post menuhax_manager.log if it still fails?

**Comment by desmond1495** [comment]
I have reinstalled and tested but still failed.
I have attached the log file for your reference. Thank you for assisting!
[menuhax_manager.zip](https://github.com/yellows8/3ds_homemenuhax/files/462234/menuhax_manager.zip)

**Comment by yellows8** [comment]
Can you be more specific with "could not boot into the Home Brew Menu with L button"?

**Comment by desmond1495** [comment]
Oh is basically the Home Brew Menu wasn't triggered after I pressed power and then hold L button, which I suppose is to trigger the Home Brew Menu.

**Comment by desmond1495** [comment]
It stays at the screen with the 'Power Off', even after i hold L button

**Comment by yellows8** [comment]
You're only supposed to hold the PAD-trigger at hard-boot .........

**Comment by desmond1495** [comment]
Thank you very much. I wasn't aware that it was to hold on hard boot. I have tested and it is working fine. I appreciate the time and effort you took.
