### ISSUE TITLE
Failed to download config: 0xfffffffe

### ISSUE THREAD

**Issue by ZenMonster525** [yellows8/3ds_homemenuhax#201]
When I try to download menuhax_manager it says that menuhax_manager build's version doesn't match the version from config or I'm likely not using the latest release version. Do I need to update or is this just a network error?

**Comment by bethanysam09** [comment]
Same problem here. I am on the old 3DS XL. What steps can I take to fix this?

**Comment by yellows8** [comment]
https://github.com/yellows8/3ds_homemenuhax/releases
