### ISSUE TITLE
"Parsing config..." stuck

### ISSUE THREAD

**Issue by ryancwxu** [yellows8/3ds_homemenuhax#202]
Hey yellow,

I had the menuhax working, but I messed up the downgrade so i reformatted to restart. however, now I keep getting stuck at "Parsing config..." when trying to install menuhax. Is there any known issues of this or fix? Can't seem to find any on the issues.

Thanks in advance

**Comment by yellows8** [comment]
Log?

**Comment by ryancwxu** [comment]
menuhax_manager v3.1 by yellows8.
Deleting SD data from old menuhax_manager versio
ns, etc...
Opening extdata archives...
Finished opening extdata.

Downloading config via HTTPC...
Parsing config...

That's where it stays. It's been like that for a few hours. I've tried about four or five times then just left it there.

**Comment by ryancwxu** [comment]
![image](https://cloud.githubusercontent.com/assets/15788886/18466745/7a110eca-7962-11e6-9e88-fba3a06af679.png)

**Comment by stoneddoom** [comment]
i'm having the same problem, on N3DS XL 10.7 (well, i'm now on 9.2 but when I try to configure menuhax_ manager it gives me the same  parsing config... )

**Comment by TankedThomas** [comment]
Same problem here on my N3DSXL 11.0.0-33E OFW.

I checked my log file but it's completely empty and I've run menuhax multiple times at this point.

I tried running ctr-httpwn beforehand to see if the cause was an internet connectivity problem but that doesn't appear to be the case.

**Comment by luceried** [comment]
Hello. This also happened to me. I used them yesterday for Gateway and they worked just fine. Today, i want to change my sd card, so i setup again using new card and this happened. Mine is O3DSXL 9.0.20U

**Comment by Kyle2100** [comment]
same thing any fixes ?  needed more space for Arm9lh so just formatted everything and switched SD cards and couldnt load menu hax.  would downgrading to like 8.0 then back to 9.2 work?

**Comment by Kyle2100** [comment]
I have formatted my system and sdcard card multiple times and no luck

**Comment by Xeleron** [comment]
I have the same issue. I tried to do this on a new 2DS running on 9.9

**Comment by Webbeh** [comment]
Same issue, stuck forever at "parsing config", brand new N3DS 9.0.0-20E right out of the box.

**Comment by Webbeh** [comment]
@yellows8 Is it due to the downloaded "config" file having a trailing space, reporting a wrong length ?

**Comment by yellows8** [comment]
" trailing space, reporting a wrong length ?" Huh?

**Comment by Webbeh** [comment]
https://yls8.mtheall.com/menuhax/config

There's a trailing space at the end of the file.

```
ret = http_download_content("https://yls8.mtheall.com/menuhax/config", &configsize); <- this saves the config size in "configsize" var
```

what if the While loop in the parse_config function never ends due to that ? 

EDIT: seeing that that file has been last modified on the third of june, I'm starting to doubt that idea.

**Comment by Kyle2100** [comment]
@webehh it worked fine until I formated SD and system after needing more room to completing the installation on Arm9

**Comment by Webbeh** [comment]
@Kyle2100 if the issue doesn't only happen on your system, it means something else is the cause ;P

**Comment by yellows8** [comment]
FWIW this won't be worked on until I'm done with v11.1 code-RE.

**Comment by Kyle2100** [comment]
@webbeh oh ik but it has worked on multiple of my devices and the one I'm using now. But after formatting it doesnt. Just waiting for a fix so I can install Arm9lh

**Comment by Xeleron** [comment]
Any ETA on "v11.1 code-RE"?

**Comment by Webbeh** [comment]
@Kyle2100 You formatted, therefore deleting the cached files in your SD card, which have then to be redownloaded. And if the files that are redownloaded aren't the same, it's not due to the format.

If 3.0 worked for you, I just got it working on my N3DS by using a copy of the SDCard of another 3DS I "hacked" a few weeks ago. So if you have another 3ds with an working version of Menuhax, just copy-paste the contents of that SD Card, after assuring that it works with your 3DS, of course.

**Comment by Darius20103104** [comment]
it happened all at once to all my 3ds's

**Comment by Darius20103104** [comment]
i think something is going on with yellows servers

**Comment by Kyle2100** [comment]
@webbeh ok good I have a 2 3ds that's running 11.0 but has menuhax installed so would that be ok?

**Comment by Webbeh** [comment]
You'll have to make sure it works with your 3ds, I can't look that up for you. If the 3ds you want to use menuhax on is compatible with the version of menuhax you have as backup, then it will work...

If you're not sure, I'd recommend waiting, I don't want to be the cause of a brick. But if you're sure, then go ahead and copy-paste the SD card contents.

**Comment by xusoize** [comment]
i have the same issue, but atm i couldnt solve, please post some solutions -.-

**Comment by Kyle2100** [comment]
@yellows8 could u fix this? I really want to install arm9 but want menuhax working first

**Comment by Kyle2100** [comment]
@webbeh do u think it's just the servers messing up?

**Comment by xusoize** [comment]
care with the new update on the 3ds guys, i updated cause i though can do nothing for open the navigator to open the hombrew, but i messed up-.-, so take care

**Comment by xusoize** [comment]
the update is the 11.1.0-34E and.... block all the hax's

**Comment by Luciano-Gert** [comment]
Same problem with a N3DS from SysNand 9.2.0-20U

I was trying to update from previous 2.2 version. The old version still works.

**Comment by ghost** [comment]
If you're setting up a9lh, don't worry about menuhax. You can just use the homebrew entrypoint 2 or 3 times andyou won't need it anymore. Menuhax is just to get the homebrew menu open more conveniently.

**Comment by Xeleron** [comment]
@Icarus77 I can't get am:u with browserhax for sysdowngrader I think.

**Comment by yellows8** [comment]
I fixed this by removing a module which menuhax_manager(public/local) doesn't have from the server config. Will fix it in menuhax_manager later(https://github.com/yellows8/3ds_homemenuhax/blob/master/menuhax_manager/source/menuhax_manager.c#L841-L848).

**Comment by Webbeh** [comment]
Thank you very much !

**Comment by Kyle2100** [comment]
@webbeh so it works now?

**Comment by Webbeh** [comment]
@Kyle2100 Compiling in a moment, will edit this post later.

EDIT: actually, will continue by private message. Anyone interested, contact me, weby@we-bb.com.

**Comment by Kyle2100** [comment]
@webbeh ok good that's means I can install arm9lh tonight:)

**Comment by Luciano-Gert** [comment]
Some one can compile this ? I tried but without success...

**Comment by Webbeh** [comment]
Struggling to find the correct versions of libraries (devkitARM, libctru, miniunzip, ...). If yellows8 could help me there, would be nice.

**Comment by Kyle2100** [comment]
@webbeh once it is compiled how can we get it?

**Comment by yellows8** [comment]
"compiling" wat

EDIT: v3.1 works fine now with the server-side change.....

**Comment by Webbeh** [comment]
```
                                                                                  Thememanager and menuhax.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        From: yellows8Sent: Wednesday, 14 September 2016 05:20To: yellows8/3ds_homemenuhaxReply To: yellows8/3ds_homemenuhaxCc: Nicolas Glassey; MentionSubject: Re: [yellows8/3ds_homemenuhax] "Parsing config..." stuck (#202)"compiling" wat
```

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.

{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/yellows8/3ds_homemenuhax","title":"yellows8/3ds_homemenuhax","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/yellows8/3ds_homemenuhax"}},"updates":{"snippets":[{"icon":"PERSON","message":"@yellows8 in #202: \"compiling\" wat"}],"action":{"name":"View Issue","url":"https://github.com/yellows8/3ds_homemenuhax/issues/202#issuecomment-246894905"}}}

**Comment by yellows8** [comment]
There's no need to build it yourself atm...

**Comment by Kyle2100** [comment]
I got arm9lh now no need for it lol R.I.P Harambe
