### ISSUE TITLE
Menux hax 3.1 Parsing config...

### ISSUE THREAD

**Issue by Kyle2100** [yellows8/3ds_homemenuhax#203]
when trying to install menuhax i will load it up then it says:

Menuhax_manager v3.1 by yellows8
Deleting SD data from old menuhax_manager versions
etc...
opening extdata archives...
finished opening extdata.

Downloading config via HTTPC...
parsing config...

and it wont do anything else pls help i needed more room on sd card while i had it all installed to formatted my sd and system and put a new one in and started over, thats when i got this error

**Comment by Kyle2100** [comment]
on version 9.2

**Comment by yellows8** [comment]
#202
