### ISSUE TITLE
I can't upgrade to menuhax 3.1

### ISSUE THREAD

**Issue by Liger0** [yellows8/3ds_homemenuhax#204]
I had menuhax 3.0 working fine, today I was going to upgrate to v3.1 but It remains locked at

_Downloading config via HTTPC....
Parsing config..._

Another "problem" is that I used ctr-httpwn for the new nintendo update but I can't use correctly this because when I try to go home I can only go restarting because if I go to the home without a reboot then I remain locked again.

**Comment by Kyle2100** [comment]
Same any fixes?

**Comment by yellows8** [comment]
#202 "Another "problem" is that I used ctr-httpwn  ..." README
