### ISSUE TITLE
parsing config

### ISSUE THREAD

**Issue by xusoize** [yellows8/3ds_homemenuhax#206]
menuhax_manager v3.1 by yellows8.
deleting sd data old menuhax_manager versions
       etc...
opening extdata archives...
finished opening extdata.

downloading config via httpc...
parsing config...

---

and then it freeze, it dont show me if i want to install or something, just shows "parsing config..." all the time, what can i do for solve this issue?

**Comment by xusoize** [comment]
@yellows8 if u can anwser fast pls....

**Comment by ghost** [comment]
I have this same exact issue with the menuhax from the starter pack. Came here to post the same thing too, glad I' not the only one experiencing it.

**Comment by xusoize** [comment]
i will glad more @Icarus77  if someone can solve this and say me what i have to do

**Comment by ghost** [comment]
I simply said screw menuhax and went and installed OoThax (hacked ocarina of time save) as my entrypoint. If you can still use browserhax or whatever entrypoint you used to get into homebrew, maybe just keep doing that for now. It's what I did for OoThax and now I'm past the downgrading.

**Comment by yellows8** [comment]
#202
