### ISSUE TITLE
CIA error pls help

### ISSUE THREAD

**Issue by Kyle2100** [yellows8/3ds_homemenuhax#208]
trying to isntall a cia and get this error 
Failed to install cia
Result Code: 0xD8E0806A
Level: Permanent (27)
Summary: Invalid Argument (7)
Module: AM (32)
Desc: Cert signature or hash check failed (106)

any fix? and FBI is updated and the cia is sysupdater trying to get Arm9lh

**Comment by yellows8** [comment]
"cia" "menuhax"

**Comment by Kyle2100** [comment]
@yellows8 could u be more clear? very new to this

**Comment by Kyle2100** [comment]
@yellows8 i have sysupdater in Browser hax so i can downgrade the rednand to 2.10 so do i need to launch rednand then browserhax or does it not matter?

**Comment by yellows8** [comment]
This has _nothing_ to do with this repo.

**Comment by Kyle2100** [comment]
@yellows8 well could u just tell me i cant find it anywhere.  Do i need to launch rednand then launch browserhax to downgrade it or could i launch browser hax on sysnand and do it?
