### ISSUE TITLE
Can't use Start and X to return to home menu

### ISSUE THREAD

**Issue by Multipixelone** [yellows8/3ds_homemenuhax#213]
The title says most of my problems. A lot of apps also hang on a yellow bottom screen too, and it just doesn't work. Its really annoying and I would appreiciate any help ;)

**Comment by yellows8** [comment]
README

"A lot of apps also hang on a yellow bottom screen too," [*hax payload](https://github.com/smealum/ninjhax2.x) needs updated for running under titles with codebin-physmem-randomization.

**Comment by Multipixelone** [comment]
Sorry I was so ignorant, I was kind of in a rush to get the comment typed, thanks again, and sorry :(

**Comment by Multipixelone** [comment]
Little nooby, is there an easy way to do that?

**Comment by yellows8** [comment]
Huh?

**Comment by Multipixelone** [comment]
How can I update the *hax payload?

**Comment by yellows8** [comment]
I meant codebase not user-side...

**Comment by Multipixelone** [comment]
Oh sorry for wasting your time :P
