### ISSUE TITLE
Can't Install Custom Themes

### ISSUE THREAD

**Issue by GeneralSummer** [yellows8/3ds_homemenuhax#214]
Hi! I'm trying to install a custom theme but the option (Install Custom Theme) doesn't appear! I installed MenuHax 2.0 and then I installed the latest version,I even have a theme ready in the [3ds/menuhax_manager] directory but it won't appear and I don't know what else to do V.V"

**Comment by yellows8** [comment]
You don't need to use menuhax_manager to install that on >=v10.6.

**Comment by GeneralSummer** [comment]
I'm on v11.0,how can I install custom themes in that version with MenuHax? :S
@yellows8

**Comment by yellows8** [comment]
You're supposed to use other custom-theme installation tools.

**Comment by GeneralSummer** [comment]
@yellows8 
Could you tell me what other tools I can use? I don't want to risk loosing MenuHax like with CHMM...

**Comment by yellows8** [comment]
That's what you're supposed to use.

**Comment by GeneralSummer** [comment]
@yellows8 
But wouldn't I loose access to MenuHax with CHMM? At least that is what happened last time (although it was a long time ago,I don't know if it changed...)

**Comment by yellows8** [comment]
no

**Comment by GeneralSummer** [comment]
@yellows8 
OK! Thanks for everything! ^^
