### ISSUE TITLE
Another person with an issue. Log inside.

### ISSUE THREAD

**Issue by garrettin** [yellows8/3ds_homemenuhax#215]
I have tried for hours to fix this by myself but have had no luck, so hopefully this post works out. I have tried the latest version and have deleted the extdata folder and went into the them section to let it initiate again. Here is my log.

menuhax_manager v3.1 by yellows8.
Deleting SD data from old menuhax_manager versions, etc...
Opening extdata archives...
Finished opening extdata.

Downloading config via HTTPC...
Config download failed(0xd8a0a046), trying to load it from SD...
Failed to load config from SD: 0x00000002.
Failed to load config: 0x00000002.

An error occured. If this is an actual issue not related to user failure, please report this to here if it persists(or comment on an already existing issue if needed), with the file from SD 'menuhax_manager.log'(normally located at '/3ds/menuhax_manager/' unless the app is running from elsewhere): https://github.com/yellows8/3ds_homemenuhax/issues
Press the START button to exit.

Thanks for your time.

**Comment by yellows8** [comment]
Network fail......

**Comment by garrettin** [comment]
Is that something on my end or should I just try again later?

**Comment by yellows8** [comment]
Former.....

**Comment by garrettin** [comment]
Is there something I need to do to fix that? Everything else seems to work fine.

**Comment by kostantinpappas** [comment]
i have the same problem you find  a solution  ???
