### ISSUE TITLE
Failed to download config

### ISSUE THREAD

**Issue by kostantinpappas** [yellows8/3ds_homemenuhax#219]
Whenever I try to install menuhax v3.1, I  getting the error message failed to load config it gives me this message 

menuhax_manager v3.1 by yellows8.
Deleting SD data from old menuhax_manager versions, etc...
Opening extdata archives...
Finished opening ext data

Downloading config via HTTPC...
Config download failed(0xd8a0a049), trying to load it from SD...
Failed to load config from SD: 0x00000002.
Failed to load config: 0x00000002.

An error occured. If this is an actual issue not related to user failure, please report this to here if it persists(or comment on an already existing issue if needed), with the file from SD '/3ds/menuhax_manager/menuhax_manager.log': https://github.com/yellows8/3ds_homemenuhax/issues
Press the START button to exit. 

my 3ds firm version is 9.6.0 24E PLEASE HELP ME

**Comment by Lattaz** [comment]
So was this fixed or not because im in a similar situation with 3ds firm version 9.8.0.25E

**Comment by leboman** [comment]
he doesnt really provide a solution...

**Comment by yellows8** [comment]
"duplicate"

**Comment by kostantinpappas** [comment]
try it with lower menuhax ver use menuhax ver 2.2 it worked  for me
