### ISSUE TITLE
Downloading config via HTTPC...  ERROR

### ISSUE THREAD

**Issue by ghost** [yellows8/3ds_homemenuhax#221]
menuhax_manager v3.1 by yellows8.
Deleting SD data from old menuhax_manager versions, etc...
Opening extdata archives...
Finished opening extdata.

Downloading config via HTTPC...
Config download failed(0xd8a0a049), trying to load it from SD...
Failed to load config from SD: 0x00000002.
Failed to load config: 0x00000002.

An error occured. If this is an actual issue not related to user failure, please report this to here if it persists(or comment on an already existing issue if needed), with the file from SD 'menuhax_manager.log'(normally located at '/3ds/menuhax_manager/' unless the app is running from elsewhere): https://github.com/yellows8/3ds_homemenuhax/issues
Press the START button to exit.

**Comment by yellows8** [comment]
#218
