### ISSUE TITLE
MenuHax config file location?

### ISSUE THREAD

**Issue by TheRasPiGuy** [yellows8/3ds_homemenuhax#224]
I know the server is down (AGAIN), but is there a way to download/create the config file manually and place it on the SD card?

**Comment by TheRasPiGuy** [comment]
Btw I have an O3DS, red (don't know if that matters), with 11.0.0-33U firmware, booting with Ninjhax. I do not have a cfw, but I really want one. (If some one knows how to install on 11.0, please tell me!)

**Comment by yellows8** [comment]
#218
