### ISSUE TITLE
Menuhax_Manager 3.1 error 

### ISSUE THREAD

**Issue by Cyberdeamon04** [yellows8/3ds_homemenuhax#228]
Good Morning,
my English is not that good.
I have a 3DS XL with the firmware 9.4.0-9E.

If I have made the browser hax I'm at homebrew in it.
I would then install menuhax_manager comes this error:

Menuhax_manager v3.1 by yellows8.

Deleting SD data from old menuhax_manager versions, etc ...

Opening extdata archives ...
Finished opening extdata.

Downloading config via HTTPC ...

Config download failed (0xd8a0a03c), load to load it from SD ...

Failed to load config from SD: 0x00000002.

Failed to load config: 0x00000002.

An error occured. If this is an issue,
Please report it to here if it persists
Issue if needed), with the file from SD 'menuhax_manager.
Log '(normally located at' / 3ds / menuhax_manager / 'unless the app
Is running from elsewhere):
https://github.com/yellows8/3ds_homemenuhax/issues
Press
The START button to Exit.

Firewall is free

Please help and many thanks

**Comment by simonrule** [comment]
same problem here

**Comment by akameister** [comment]
Same here
New3DS 11.2.0-35E

Failed to download 0xd8a0a049
Failed to load config from SD: 0x00000002

Is there a config to drag it on the sd ?

Edit: draged the config to the SD still failed to load from SD: 0x00000002
