### ISSUE TITLE
Offline Installer?

### ISSUE THREAD

**Issue by Syphurith** [yellows8/3ds_homemenuhax#23]
Hi Yellow. Thanks for your work first. I have some issues with the git-version of the installer, as below.
- It seems the latest version (2b2c689422519ce6425e95c642192f4c2ee8e3fb) of themehax_installer can not parse the latest 2.5 payload correctly. It just tells me `Failed to parse the payload: 0xfffffffb.` Then installation failed.
- However it seems if i use an older version of the payload, that the corresponding file from the otherapp folder of a legacy offline version of the themehax_installer (from gbatemp, v1.2), it installs.
- An offline version of the themehax_installer, without touching the network is badly needed. Not all the guys can get it downloaded easily in several tries. (I saw guys doubting if the site is down..)

I suggest you consider to make an official offline version. You may not have enough time to adapt the new payloads in time.  ~~And CIAs, I would not bother you. I thought i should ask Dean_ for the rsf..~~

**Comment by yellows8** [comment]
The app already supports loading an input payload from SD, so not sure what you're on about.

"can not parse the latest 2.5 payload" Of course not. This is not an issue with my local-changes(which was done before 2.5 was ever released).

**Comment by Syphurith** [comment]
Well i think if they remember to collect the correct payload files and prepare the package before installation, thus offline issue could be regarded as solved. Then, I'd just wait for the 2.5 adjustments..

**Comment by Syphurith** [comment]
Pity for those just plan to install themehax now. ~~They have to get the 1.2 offline version and load via HBL. Since it is not adjusted to 2.5 payload yet, it would accept old payload, and not for the themedata with it.~~
