### ISSUE TITLE
Can you help instead of just closing and ignoring? 

### ISSUE THREAD

**Issue by leboman** [yellows8/3ds_homemenuhax#231]
Hey man I guess youre a busy man however its really difficult to use your program and you kind of just closed my previous thread with zero explaination whatsoever, it seems youre like that with everybody however do you reckon you could let me know whats going on here... I mean if its a basic thing that noob should know im sure youd have no issue delivering it to me in a condescending fashion - ill settle for it 

menuhax_manager v3.1 by yellows8.
Deleting SD data from old menuhax_manager versions, etc...
Opening extdata archives...
Finished opening extdata.

Downloading config via HTTPC...
Error: server returned HTTP statuscode 403.
Config download failed(0xfffffffe), trying to load it from SD...
Failed to load config from SD: 0x00000002.

Failed to load config: 0x00000002.

An error occured. 
If this is an actual issue not related to user failure, please report this to here if it persists(or comment on an already existing issue if needed), 
with the file from SD 'menuhax_manager.log'(normally located at '/3ds/menuhax_manager/' unless the app is running from elsewhere): https://github.com/yellows8/3ds_homemenuhax/issues

Press the START button to exit.

What is happening lol? There are many people who ask this question but you seem to shut them down, is there no solution - i did also mention on my previous post that i am ver10.6.0-31E , maybe that would be useful?

**Comment by yellows8** [comment]
"There are many people who ask this question but you seem to shut them down" <- It's called "duplicate" for a reason...
