### ISSUE TITLE
Menuhax v3.1 error (see pic)

### ISSUE THREAD

**Issue by leboman** [yellows8/3ds_homemenuhax#232]
Hey all I am at my wits end, tried the config and everything else. Surely somebody has come across this issue as well. 

Please help lol. At my wits end here.
![15226347_10157853269335319_462855777_n](https://cloud.githubusercontent.com/assets/24217790/20672416/59820060-b5d5-11e6-934a-2a7e28ef6d74.jpg)

**Comment by yellows8** [comment]
#218
