### ISSUE TITLE
please help. error occured.

### ISSUE THREAD

**Issue by xczsonn** [yellows8/3ds_homemenuhax#236]
menuhax_manager v3.1 by yellows8.
Deleting SD data from old menuhax_manager versions, etc...
Opening extdata archives...
Failed to open theme extdata with extdataID=0x000002cc, retval: 0xc8804464
Exit this app, then goto Home Menu theme-settings so that Home Menu can create the theme extdata.

An error occured. If this is an actual issue not related to user failure, please report this to here if it persists(or comment on an already existing issue if needed), with the file from SD 'menuhax_manager.log'(normally located at '/3ds/menuhax_manager/' unless the app is running from elsewhere): https://github.com/yellows8/3ds_homemenuhax/issues
Press the START button to exit.
-------------------------------------------------------

how can i should do?

**Comment by yellows8** [comment]
Actually *read* the message .....

**Comment by xczsonn** [comment]
wow, i am a really stupid
