### ISSUE TITLE
menuhax issue

### ISSUE THREAD

**Issue by Vino-24** [yellows8/3ds_homemenuhax#238]
menuhax_manager v3.1 by yellows8.
Deleting SD data from old menuhax_manager versions, etc...
Opening extdata archives...
Finished opening extdata.

Downloading config via HTTPC...
Config download failed(0xd8a0a049), trying to load it from SD...
Failed to load config from SD: 0x00000002.
Failed to load config: 0x00000002.

An error occured. If this is an actual issue not related to user failure, please report this to here if it persists(or comment on an already existing issue if needed), with the file from SD 'menuhax_manager.log'(normally located at '/3ds/menuhax_manager/' unless the app is running from elsewhere): https://github.com/yellows8/3ds_homemenuhax/issues
Press the START button to exit.

pls help

**Comment by furiak** [comment]
same error here

**Comment by Vino-24** [comment]
I solved it mate, fortunately plailect edited the guide for n3ds fw>10.7. I
used fiddler to block the website and then followed the instructions in the
guide. I have cfw now on my 3ds. Thanks!

**Comment by fox8091** [comment]
If solved, please close.

**Comment by furiak** [comment]
Same error here but resolved after realizing I wasn't removing the blocked website after the menuhax loaded

**Comment by Vino-24** [comment]
Yup that was how i solved it too. Do you have cfw now m8?

**Comment by furiak** [comment]
Yup works great
