### ISSUE TITLE
Fail to launch

### ISSUE THREAD

**Issue by Reedkaan** [yellows8/3ds_homemenuhax#239]
Hi,

I've downloaded the version 3.1 of Menuhax and installed it. I'm on 9.2.0-20E Firmware on a old 3DS.

When i'm installing and relaunching my 3ds, i've got a black screen ... I can't do nothing and I have to unplug my SD card to go to the main menu... I've tried to configure the PAD file but nothing changes...

What Have I done wrong?

Thanks by advance

( BTW i can't even launch Rx tools or Gateway with browser... There's also a black screen , with all versions I've tested... Is there possible my firmware or installation has a problem? )

**Comment by yellows8** [comment]
No idea, try reinstalling or so.

**Comment by Reedkaan** [comment]
I already tried a lot of times, with all the versions but it's the same... There's everytime a black screen to the launch of the 3ds...
