### ISSUE TITLE
Unable to load at boot time, but can boot from sleep mode screen

### ISSUE THREAD

**Issue by gingerbeardman** [yellows8/3ds_homemenuhax#24]
Not sure if this is an issue with themehax, or with smealum payload.

I have a N3DS running 10.1.0-27E and am unable to boot hax from power on by holding L (freezes at grey screen) but can boot from sleep mode screen by pressing Home then holding L (with green flash). 

I've read other scattered reports of this issue on neogaf and gbatemp.

Any ideas?

Here's a video: http://cl.ly/2E2a3C013Z2B
(ignore that the video makes it looks like static is moving, it's not)

Thanks!

**Comment by yellows8** [comment]
What menuhax/payload versions?

**Comment by gingerbeardman** [comment]
Apologies, originally installer 1.2

Upgraded to hax 2.5 manually

**Comment by yellows8** [comment]
Normally I'd assume you setup the payload wrong but in this case it works from post-initial-menu-load, so...

**Comment by gingerbeardman** [comment]
Yes, that's the confusing thing.

**Comment by vaguerant** [comment]
I mentioned this in IRC already, but it's probably worth saying somewhere less transient. I see very similar behavior on a 9.9.0 USA New 3DS. I have Themehax installed via the version 1.2 installer and the 2.5 payload from smea's site. Trying to cold boot into Themehax (holding L) I will most often crash on the yellow bottom screen. Occasionally--perhaps one in 10 or so attempts--I pass the green and then yellow screens (I think, it's all quite fast obviously) then get the following stock Nintendo error:

```
        An error has occurred.
    Hold down the POWER button to
 turn off the power, then turn it on
          and try again.

For help, visit support.nintendo.com.
```

I haven't once booted successfully into the Homebrew Launcher with 2.5 from a cold boot, while I had only very infrequent issues with the 2.1 payload (maybe two or three failures total in the tens or maybe hundreds of times running it).

If I boot via Power, Home, L, I'm able to reliably get into the Homebrew Launcher (stock smealum boot.3dsx from the latest starter). Likewise, I have only very infrequent issues getting into the Homebrew Launcher using Ironhax (installed to version 1.1 from the latest starter also).

**Comment by yellows8** [comment]
Works fine on my New3DS, it hardly ever hangs. Old3DS though...... :|

**Comment by yellows8** [comment]
Not much that can be done to fix/debug the gray/white screen issue since it rarely hangs like that on my New3DS(unless it's somehow fixed in the next release of course).

**Comment by yellows8** [comment]
NVM, this should be fixed in next release(on Old3DS at least), let me know if it's fixed on New3DS.

**Comment by thedax** [comment]
For me 2.0's booting rate is even worse than 1.3 with a hax 2.5 payload. It auto boots maybe 10% of the time on my 9.0.0-20U N3DS.

**Comment by yellows8** [comment]
I don't even remember the last time I tested it on New3DS <=v9.2 tbh, guessing it's system-version related since it almost always works on New3DS v10.1 AFAIK.

**Comment by thedax** [comment]
It might just be my console or something, I saw someone else on GBAtemp say they're on 9.0.0E and have no issues with it. I've reverted back to 1.3 with a hax 2.1 payload for now, since it boots about 95% of the time.

**Comment by vaguerant** [comment]
Just confirming Menuhax 2.0's vastly improved compatibility on my end. Haven't had it fail yet, using the default top-screen image.

**Comment by yellows8** [comment]
@thedax Can you describe every hang you ever had with v2.0?(screen color / whatever)

**Comment by thedax** [comment]
> @thedax Can you describe every hang you ever had with v2.0?(screen color / whatever)

Sure, all hangs have been the exact same. Whenever 2.0 hangs on this console, the "The Menuhax Loader" logo displays, and the bottom screen is white. I use type1 button config with no buttons set, so it automatically boots when I turn the power on. 

Here's how I installed it for this post:
1. Let themehax 1.3 autoboot into Smealum's 2.5 HBL (using 2.1 payload)
2. Ran the installer and picked Type1 buttons with no buttons set for autobooting.
3. Went down to the image installer and installed the default picture by Louch.

The boot rate seems to be a little better this way, freezing roughly 1 in 3 times. When I try to use other suggested methods, like going into the theme settings in the home menu, the boot rate drops back down to roughly 1 in 10 tries.

**Comment by gingerbeardman** [comment]
I used your 2.0 updater which has given me the file `ropbinpayload_menuhax_EUR20480_new3ds.bin`

I can now launch from boot hiding L, but not every time. 

Failure is on grey screen, infrequently.

Same with loading from Settings holding L after pressing X to close.

**Comment by thedax** [comment]
Maybe it's just placebo effect, but the new payloads that @smealum released like an hour ago seem to have fixed my problem. I've had over 5 successful boots of menuhax 2.0 so far, in a row, but I'm still testing.

**Comment by gingerbeardman** [comment]
@thedax thanks for the info! looking good. 3 successful boots out of 3.

for anybody else wondering, you get the latest payloads by running the homemenuhax installer again.

**Comment by gingerbeardman** [comment]
Just booted from cold (ie. not used device for 18 hours) and got grey screen holding L on boot. Twice. :cry: 

Booting rom Settings worked fine.

**Comment by yellows8** [comment]
*from System Settings?

Anyway, that's an issue with the payload really.

**Comment by gingerbeardman** [comment]
@yellows8 yes from System settings. 

I'll try the latest payload, but where and how should I report a bug against it?

**Comment by yellows8** [comment]
No need to report anything elsewhere.

**Comment by gingerbeardman** [comment]
@yellows8 thanks. FWIW tonight I updated to latest starter pack, reinstalled homemenuhax and even replaced my top manually. still getting grey screen often, even from System Settings.
