### ISSUE TITLE
MenuHax Installation Failure Issue

### ISSUE THREAD

**Issue by ghost** [yellows8/3ds_homemenuhax#240]
This is the issue I'm getting: 
"Downloading config via HTTPC...
Config download failed (0xd8a0a049), trying to load it from SD...
Failed to load config from SD: 0x00000002.
Failed to load config: 0x00000002."
I checked my SD card and it did not make a config error file. ( I looked everywhere, in /3ds. /menuhax, /menuhax_manager, etc )

**Comment by yellows8** [comment]
User network-fail.
