### ISSUE TITLE
Menuhax_manager installation step fails. Have read post #218 and README.

### ISSUE THREAD

**Issue by Snoddas76** [yellows8/3ds_homemenuhax#246]
Hi,
I'm sorry if a solution to this problem has already been presented in the #218 post or the README but i went through the post several times but can't figure out if i have missed something.

1. I have the 3.1 version of menuhax_manager on my SD-card. 
2. I am using a US N3DS running 11.2.0-35U.
3. I opened the Theme settings on my 3DS from the Home Menu as suggested.
4. I first had the config-file download issue. I downloaded the "config" file that @wwwwwwzx posted in the #218 post and put it in the right folder which solved the config-file issue.
5. I downloaded the Ropbin payload from [https://smealum.github.io/3ds/](https://smealum.github.io/3ds/) for my version. I renamed the file "menuhaxmanager_input_payload.bin" and have tried putting it on the SD-card Root, in the /menuhax/ folder and also the /menuhax/ropbin folder.
6. When installing i choose option A both times when asked but still get the following error after setting my system-version:

"Using the selected system-version: New3DS 11.2.0-35 USA
Sending network requests...
First URL: https://yls8.mtheall.com/ninupdates/get_reportinfo.php?sys=ktr&updateversion=11.2.0&format=raw&info=reportdate
Initial HTTPC request failed: 0xd8a0a046.
Install failed: 0xd8a0a046."

See the attached file for the full log.
[menuhax_manager.log.txt](https://github.com/yellows8/3ds_homemenuhax/files/694031/menuhax_manager.log.txt)

**Comment by yellows8** [comment]
https://www.3dbrew.org/wiki/HTTP_Services#Error_codes

**Comment by yellows8** [comment]
"11.2.0-35" You can't use menuhax currently anyway....

**Comment by Snoddas76** [comment]
@yellows8 Thank you for that link, i hadn't seen it.

Oh really, i must had read the comments #218 wrong then, i thought i saw someone using menuhax on 11.2.0-35 with success. That is good to know at least. Any ETA on an update working with my version?

**Comment by yellows8** [comment]
;-)
