### ISSUE TITLE
menuhax not installing o3ds

### ISSUE THREAD

**Issue by NuclearDuck13** [yellows8/3ds_homemenuhax#247]
o3ds v11.2.0-35u
install works just fine up to BOSS setup.

I've updated and run httpwn 1.2 and updated to menuhax 3.2. My home menu theme is just blank.
What's wrong?

EDIT: forgot to attach log lol

[menuhax_manager.zip](https://github.com/yellows8/3ds_homemenuhax/files/697665/menuhax_manager.zip)

**Comment by yellows8** [comment]
It does say "network failure", just try again....(ctr-httpwn has to be run right before menuhax_manager)

**Comment by NuclearDuck13** [comment]
THANK YOU. I didn't realize ctr-httpwn had to be run right before. For some reason I was under the impression that you run it once and it's good. Problem Solved!
