### ISSUE TITLE
Menuhax_Manager v3.2 Error

### ISSUE THREAD

**Issue by Zaiphon** [yellows8/3ds_homemenuhax#248]
Hey everyone, maybe someone of you guys can help me with my Issue.

Firstly i did everything straight down as described in the install README. (I dont think i did something wrong).

I tried to install/start menuhax_manager v3.1 via browserhax on my O3DSXL Version 10.4.29E.
As a normal thing to happen it gives me an Error "This menuhax_manager build's version doesn't match the version from the config." which means get the new one [v3.2]

Copied the new content onto my SD card, tried it again via Browserhax menu says v3.2 which means i copied atleast right.

Now the Error which i dont get past.

Before the v3.2 it atleast showed me text, now it gives me a RED Screen and nothing happens, idk what this could be, an ideas?

Regards

**Comment by yellows8** [comment]
Title-takeover fail, just try again.

**Comment by Zaiphon** [comment]
Tried it a few times now, didnt changed a thing, still stays red on the touch screen. Change the Date and time to 1.1.2000 / 00:00, deleted cookies and history and resettet my browser to no avil.

**Comment by yellows8** [comment]
It's just \*hax payload, keep trying and make sure it's \*hax payload >=v2.8.

**Comment by Zaiphon** [comment]
How/Where can i check the value for the hax payload?

**Comment by yellows8** [comment]
It's displayed during \*hax payload boot ........

**Comment by Zaiphon** [comment]
Well if you mean the boot into THL its so fast you cant read it at all.

EDIT Managed to get it 
*hax 2.8 beta

**Comment by jride1995** [comment]
what does installed failed: 0xfffffff7 mean

**Comment by xAkiyamax** [comment]
I've the exactly the same problem. Any solution?

PD: Sorry if I write something wrong, I'm spanish and I'm trying to found a solution for this problem... I've a OLD 3DS XL with 10.5.30E.

**Comment by xAkiyamax** [comment]
![img_0321](https://cloud.githubusercontent.com/assets/25106417/21938524/07e353ac-d9bc-11e6-9b6f-840bdf906cf9.JPG)
![img_0322](https://cloud.githubusercontent.com/assets/25106417/21938525/07e3924a-d9bc-11e6-8bc1-a7384b1c899e.JPG)
