### ISSUE TITLE
Can't boot menuhax without Face Raiders

### ISSUE THREAD

**Issue by Julcello692** [yellows8/3ds_homemenuhax#249]
Menuhax is great! I'm on old 3ds 11.2.0-35U A9LH + Luma and menuhax works, it just doesn't work unless I hover over Face Raiders in my Home Menu. I've tried experimenting with all the settings in the app, including type 1 and 2 in the configure menu and using the buttons I configured for each type, changing delay values to different amounts of time, and configuring a different PAD value for the menuhax thread. I experimented with 0 delay before jumping to the *hax payload, but there was the same amount of delay no matter what number I put in. Menuhax also wouldn't boot unless I hovered over Face Raiders, no matter how long I waited. Could you please let me know how to fix this? Thanks!

**Comment by yellows8** [comment]
.................................................................... README

**Comment by Julcello692** [comment]
I read it multiple times. Is it this section? If not, which one is it?

 Old3DS return-to-menu

On Old3DS with applications which trigger a firmlaunch due to requiring more memory for the APPLICATION memregion, pressing the HOME button will result in a hang due to Home Menu crashing with menuhax installed. This include Super Smash Bros, Monster Hunter as well as Pokemon Sun and Moon.

The only way this could ever be resolved is with a Home Menu vuln which doesn't involve linearmem pre-*hax-payload, unlike all of the ones used in this repo publicly currently.

**Comment by yellows8** [comment]
https://github.com/yellows8/3ds_homemenuhax#usage-notes-for-bossbannerhax

**Comment by Julcello692** [comment]
Thanks, must've missed that.
