### ISSUE TITLE
Menuhax not launching

### ISSUE THREAD

**Issue by woombadoomba** [yellows8/3ds_homemenuhax#253]
Hello,

So I just succesfully installed Menuhax after many attempts, but then when I try to launch the hax by holding the two buttons I selected in the configuration (buttons R and X), well, nothing happens ... |:
I tried to reinstall Menuhax by deleting it first, and redownloading again all the files and only the most recent files but the same thing happens ... which is nothing.
I'm using a New 3DS XL 11.2.0.35-E, with no themes and nothing so I don't understand why this doesn't work.

I had an Old 3DS before, and the hax worked perfectly back then.

Hope you can help me !

-------------------------
P.-S. : Sorry for my bad english, I'm french.

**Comment by yellows8** [comment]
README

**Comment by woombadoomba** [comment]
Oh ok it's about the Face Raiders app.
I tried but I had an error message on my 3DS then, but now I tried again and it works.

So to launch Menuhax I do have to go Face Raiders, I thought we just had to press the specified buttons like before.

-------------------------
Thank you, and sorry for not reading correctly README, but I don't understand very well english.
