### ISSUE TITLE
Menuhax

### ISSUE THREAD

**Issue by brunoflores0119** [yellows8/3ds_homemenuhax#259]
![screenshot 121](https://cloud.githubusercontent.com/assets/25727312/22865253/f5156060-f114-11e6-9803-65a0eb94a300.png)
![screenshot 120](https://cloud.githubusercontent.com/assets/25727312/22865254/f88ea242-f114-11e6-8333-63f9cb0c08ca.png)
![screenshot 119](https://cloud.githubusercontent.com/assets/25727312/22865256/fb2bc624-f114-11e6-88bd-7d65f3dfd6b4.png)
![screenshot 118](https://cloud.githubusercontent.com/assets/25727312/22865257/fdc57e3e-f114-11e6-8b6e-573778c30fcc.png)

So i updated to 11.3 because smeal said that all apps would work on it and i figured that menuhax would work too. It worked perfectly fine and then all of the sudden it lost it's icon and it just says menuhax_manager and when i try to load it, it won't work

**Comment by yellows8** [comment]
........................................ README
