### ISSUE TITLE
Request: app icon and boot image.

### ISSUE THREAD

**Issue by yellows8** [yellows8/3ds_homemenuhax#26]
It would be nice to have the following gfx. Note that if the gfx would include "themehax" at all(text or visual), "menuhax" should be used instead.

Submissions should be in PNG format. One way to send submissions is by leaving comments on this issue. Deadline is around when the next release is finished, hopefully.
- A dedicated 48x48 icon for the application included with this repo. Note that a mere {HOME + wrench} icon isn't good enough, since by the icon alone that would imply "Home Menu Settings".
- An image that will be displayed on the main-screen instead of the junk, during boot when hax is triggered. This will be the default image which can be setup by the app if the user uses the option for it. The PNG dimensions must be either 800x240 or 240x800(the latter is the framebuffer-form)."The first half of the image(in terms of pixels) is for 3D-left, the rest is for the 3D-right. The 3D-right should be same as 3D-left if no stereoscopy is used by the image."

**Comment by LunNova** [comment]
Would a {cracked HOME + being bashed with wrench} be any good? (can't draw it, sorry)

**Comment by yellows8** [comment]
Something similar to that is one option for the icon I guess.

**Comment by Journoid** [comment]
![icon](https://cloud.githubusercontent.com/assets/15371172/10806595/fef41a0e-7dac-11e5-9b40-f00822e87104.png)

Hows this? small text is hard to make but here is an icon

**Comment by Petraplexity** [comment]
![menuhax icon](https://cloud.githubusercontent.com/assets/15371170/10806613/c0e282ee-7da4-11e5-8c91-a9bc4f6e858f.png)
My entry for the 48x48 icon. It gets the point across, and it's simplistic. When smea wanted an eShop icon, I noticed a lot of people's icons were too tacky, so I tried to avoid that.
But this took like 15 minutes so I'm sure someone can do better. :P

**Comment by ben123111** [comment]
Heres one, I only realized now your not smea but whatever. Just saw you needed an icon
![menuhax](https://cloud.githubusercontent.com/assets/13081615/10806872/fb18d53e-7daf-11e5-8edb-2bc097952906.png)

**Comment by NoahMajora** [comment]
Here's what my brain created. :3 (Fixed)

![icon](https://cloud.githubusercontent.com/assets/15371439/10807214/1f7addaa-7dab-11e5-9bc0-d6c49d7ea735.png)

**Comment by NaxiD** [comment]
Here's my try

<img src="http://i257.photobucket.com/albums/hh208/NAXID/ICON_zpsrxoeatxi.png">

**Comment by yellows8** [comment]
@NaxiD Did you not read the original-comment?

**Comment by flameye** [comment]
don't really understand wat u mean with the 800x240 image, like how you want it to look.

**Comment by sam15041999** [comment]
Here's my attempt. i though it looked simple, yet creative. Gives it the HomeBrew Vibe.
![themehax fw](https://cloud.githubusercontent.com/assets/15371658/10807331/58ddb98e-7dd6-11e5-9634-aef9d9e2e93d.png)

**Comment by LunNova** [comment]
@flameye I read it as an 800x240 (widthXheight) PNG to be displayed while menuhax is loading
Split down the middle into two 400x240 images, one for each eye (left/right). If not making it 3D, both 400x240 parts should be the same.

**Comment by flameye** [comment]
Alright thanks!

**Comment by sam15041999** [comment]
Here is my attempt.. I thought i'd go with a simple, yet creative look. something that would fit the homebrew vibe.
![themehax fw](https://cloud.githubusercontent.com/assets/15371658/10807371/c65f29ca-7dd6-11e5-8661-8ec8c9d3f8db.png)

**Comment by NaxiD** [comment]
@yellows8 I'm sorry man, my english is not very good...

Here are my new tries:

<img src="http://i257.photobucket.com/albums/hh208/NAXID/MENU_zps5sqel0kl.png">

<img src="http://i257.photobucket.com/albums/hh208/NAXID/square_zpsxl6uq7hw.png">

<img src="http://i257.photobucket.com/albums/hh208/NAXID/LOAD_zpsbk77fm6c.png">

**Comment by sam15041999** [comment]
I don't understand the 800x240 part? I made this image 800x240? Is this what you were looking for?
![themehax menu fw](https://cloud.githubusercontent.com/assets/15371658/10807420/6d0964ac-7dd7-11e5-99ce-73aa3c0c83f5.png)

**Comment by yellows8** [comment]
It was described by quite well by @nallar, but here's a sample anyway:

![imagedisplay_example_new](https://cloud.githubusercontent.com/assets/585494/10807531/31733e10-7db7-11e5-920c-8c9f8b3ec646.png)

**Comment by sam15041999** [comment]
Like this? 
![themehax menu fw](https://cloud.githubusercontent.com/assets/15371658/10807623/6da9ef38-7dd9-11e5-95db-b26cd3538bff.png)

**Comment by yellows8** [comment]
Yeah that's what I mean.

**Comment by yellows8** [comment]
You shouldn't have a wrench / "settings" icon in the haxx boot image: it's just the haxx not the app.

**Comment by sam15041999** [comment]
Does this look good?
![themehax menu fw](https://cloud.githubusercontent.com/assets/15371658/10807657/df5a50d2-7dd9-11e5-8388-5cbc421021f2.png)

**Comment by flameye** [comment]
could i have some names for who created themehax? like to put at the top or bottom of my design like quite small 'created by; name, name, name, name or something like that or no?

**Comment by sam15041999** [comment]
Just make the name Yellows8

**Comment by yellows8** [comment]
See README credits section.

**Comment by flameye** [comment]
ok thanks,

**Comment by flameye** [comment]
![menuhax](https://cloud.githubusercontent.com/assets/15371424/10807769/4439949e-7ddb-11e5-81d6-26170913dc9f.png)

**Comment by NoahMajora** [comment]
"warming up" + Cool Color? XD

**Comment by LunNova** [comment]
If you want your text to pop out in 3D, offsetting it to the left a few pixels in the right side image should work. Maybe.

**Comment by NoahMajora** [comment]
My brain made this one now. xP

![icon2](https://cloud.githubusercontent.com/assets/15371439/10808500/3e7aa0f0-7dba-11e5-8798-ac0a6ab1f107.png)

**Comment by pixel-stuck** [comment]
anyone know what font the homebrew launcher uses?

**Comment by pixel-stuck** [comment]
well I don't have the font I want and it's a bit unoriginal but here it is
![menuhax](https://cloud.githubusercontent.com/assets/3634616/10808697/a8f0ca86-7dc4-11e5-8c6e-b4a56e0cb6ff.png)

**Comment by yellows8** [comment]
Looking nice so far.

**Comment by pixel-stuck** [comment]
I just saw the thing above about the 800x240 here's the new one

![menuhax](https://cloud.githubusercontent.com/assets/3634616/10808812/ec036f1c-7dc5-11e5-83a2-6e3e0294b4c1.png)

**Comment by cheatfreak47** [comment]
Spent about 20 minutes playing with stereoscopic 3d stuff, made something really nice.
![submission](https://cloud.githubusercontent.com/assets/7818664/10811794/4aef7168-7de6-11e5-9f7d-5479c52a0c4b.png)
[3DS MPO/JPG](https://u.teknik.io/vzweTA.zip)
[Red/Blue Preview](https://u.teknik.io/MJBZzO.PNG)
edit, fixed the submission image- for some reason they got swapped.
If you don't have time to view the preview I put together, the background is recessed a bit- "menuhax" pops out pretty good, and "by yellows8 and smea" pops out a little less then "menuhax"

Here's an icon too.
![menuhax](https://cloud.githubusercontent.com/assets/7818664/10809077/2c51671a-7dc9-11e5-856b-8e3acd8c2602.png)

**Comment by LunNova** [comment]
@cheatfreak47 Cool!

If you want to view the 3D on a normal screen, you can view it as a [crossview image (cross-eyed 3D)](http://www.tutorial-page.de/EN/3d-tutorial-1-an-introduction/).

**Comment by Lethaltail** [comment]
Was hoping someone could make something that resembles this dialog from SGI Irix.
(the same SGI that developed the Nintendo 64's graphics HW.)
![12 system_coming_up](https://cloud.githubusercontent.com/assets/13040464/10809808/3abc18be-7dc8-11e5-8639-9c63c63c669c.jpg)

**Comment by stonedDiscord** [comment]
![menuhax](https://cloud.githubusercontent.com/assets/10584181/10809839/e51f7e0e-7dfa-11e5-8fa9-31cdc1ba7986.png)

no comment on this one

**Comment by pixel-stuck** [comment]
Lol nice @stonedDiscord

**Comment by islandmat** [comment]
Thought that I would take a crack at it. Let me know if this is any good. I can color the background or try to modify anything if you want.
![mnuhax](https://cloud.githubusercontent.com/assets/1959186/10809850/adb48058-7ddd-11e5-9955-090fb6b05e41.png)

**Comment by Frizouy** [comment]
hi my icon [menuhax icon](https://cloud.githubusercontent.com/assets/15371270/10809813/9cbc3b8e-7dfa-11e5-9aae-8271c31dab11.png)
the software for picture 3d for 3ds  >http://www.mediafire.com/download/rlat8uhsthprtam/Create+3D+Images+JTA777.rar

**Comment by MeiFagundes** [comment]
Here is a splashscreen with 3D particles!
![menuhax splashscreen](https://cloud.githubusercontent.com/assets/15373903/10810254/1b68287c-7de6-11e5-9302-ebf4e7772f57.png)

**Comment by cheatfreak47** [comment]
@LouchDaishiteru Did a quick convert of that to MPO and it comes off to me as a bit eyestrainy on the 3DS screen. Could just be me though. I think you need to make the background recessed a bit or something like that. You can do that by shifting it over a few pixels to the left (about 8 or 9) to the left on the image for the right eye.

It's actually really good though. It's possible the eye-strain i'm experiencing is from the stripes pattern on the background.

**Comment by MeiFagundes** [comment]
I think this should fix it. I changed the pattern to one more easier to see and focus in 3D.
![menuhax splashscreen](https://cloud.githubusercontent.com/assets/15373903/10810696/a8636c88-7dea-11e5-8df2-9ad69e9721c0.png)

**Comment by cheatfreak47** [comment]
@Techinicabor Something like this? **raises eyebrow, smirking**
![preview](https://cloud.githubusercontent.com/assets/7818664/10811512/0ec9303c-7de3-11e5-9321-28be7e3a3970.PNG)
[3DS MPO&JPG](https://u.teknik.io/UqXdcx.zip)
[Red/Blue Preview](https://u.teknik.io/UNbfTz.png)

**Comment by pixel-stuck** [comment]
@yellows8 will the banner be configurable? Like if I wanted to make a custom one for myself would that be possible? I get it if it isn't but I for one would love it

**Comment by ANTONIOPSD** [comment]
![menuhaxicon](https://cloud.githubusercontent.com/assets/1978099/10814287/e75085ca-7e1c-11e5-8891-6265c0f605bd.png)

![menuhaxicon](https://cloud.githubusercontent.com/assets/1978099/10813628/5c3fe682-7e18-11e5-9841-84f4b3f9f4ef.png)

![menuhax800x240](https://cloud.githubusercontent.com/assets/1978099/10812876/4b99ec20-7e12-11e5-8429-fba4aad8fcb2.png)

Differences:

![menuhax](https://cloud.githubusercontent.com/assets/1978099/10812879/51a74f86-7e12-11e5-9230-51b42d53b0ec.gif)

zip file with everything + MPO

https://www.dropbox.com/s/1xgtcw3ku9s523h/menuhax.zip?dl=0

**Comment by altjk** [comment]
![icon](https://cloud.githubusercontent.com/assets/15377170/10814637/58c66166-7e27-11e5-86a2-6fda3733924d.png)

**Comment by lotsa-spaghetti** [comment]
Goodbye, Random VRAM Content based-Screen!

**Comment by Lethaltail** [comment]
@cheatfreak47 You hit the nail square on the head, that is amazing. c:

**Comment by yellows8** [comment]
@dark-samus The image-display menu has 3 options minus returning to main-menu: delete image-display file so that the VRAM junk is displayed, load the image from a PNG included with the .3dsx itself, or load from a PNG on SD card(the second one is what this github-issue is for).

**Comment by pixel-stuck** [comment]
@yellows8 very cool! I look forward to using it

**Comment by lotsa-spaghetti** [comment]
Sometimes the junk does not show up before it has been started. Will the same thing happen to image files?

**Comment by yellows8** [comment]
@kim-yannick Not aware of that ever happening. Image-display is done at the same time that the junk-display would have been done though.

**Comment by NoahMajora** [comment]
Meh

![menuhaxload](https://cloud.githubusercontent.com/assets/15371439/10823128/32c7e344-7e28-11e5-9a41-f612940b0731.png)

**Comment by pixel-stuck** [comment]
new stereoscopic 3D version of my above with text shadows, the water should pop out slightly then the shadows should appear on top of that and finally all text should pop more than the shadows, I also included smealum instead of smea since that's his "full" alias

Splash screen:
![menuhax stereoscopic](https://cloud.githubusercontent.com/assets/3634616/10826026/2121e624-7e3e-11e5-8309-9b46dbdf12cb.png)

Icon:
![menuhax icon](https://cloud.githubusercontent.com/assets/3634616/10828245/b9edd13c-7e49-11e5-9600-6d895cce812c.png)

SVG resource:
http://www.mediafire.com/download/tdk4sbiv37d55u8/menuhax.svg

 found the HB launcher font, it's URW Gothic L for anyone who needs to know
note that you'll need to install the above font to properly view/edit the above SVG

**Comment by flameye** [comment]
2nd attempt

![menuhax2](https://cloud.githubusercontent.com/assets/15371424/10831043/09c68970-7e7b-11e5-987a-78207a6026ae.png)

**Comment by yellows8** [comment]
The authors of the icon/boot-image will be credited in the public README(already in my local-changes).
