### ISSUE TITLE
Installed on "Custom Theme", but doesn't load Homebrew on startup with L-bumper.

### ISSUE THREAD

**Issue by iiKromium** [yellows8/3ds_homemenuhax#262]
I installed Menuhax using the "install custom theme" option in the menuhax manager. It successfully installed, but when I turned my 3DS on and off (holding the L-bumper while it was powering on), it didn't load the "menuhax" launcher, instead bringing me to the Home Menu. Not sure what to do.

**Comment by iiKromium** [comment]
Since it doesn't load on startup, I load Homebrew by going into my N3DS Sound and playing the "<3 nedwill 2016" file.

**Comment by yellows8** [comment]
details

**Comment by iiKromium** [comment]
?

**Comment by yellows8** [comment]
system-version, ....

**Comment by iiKromium** [comment]
11.3.

**Comment by iiKromium** [comment]
I have Menuhax 2.2.

**Comment by iiKromium** [comment]
It may be a problem with the PAD file.

**Comment by yellows8** [comment]
https://github.com/yellows8/3ds_homemenuhax#usage-notes-for-bossbannerhax You don't install custom-themes with menuhax_manager on v11.3.

**Comment by iiKromium** [comment]
I also tried it without a custom theme, with no avail.

**Comment by yellows8** [comment]
"on startup" README

**Comment by iiKromium** [comment]
Hmm...

**Comment by iiKromium** [comment]
Guess I'll just start it from Sound?

**Comment by iiKromium** [comment]
Unless there's a way to downgrade my system, which is highly unlikely...

**Comment by iiKromium** [comment]
Anyways, thanks for telling my retarded self that there is no boot up Homebrew start for me.

**Comment by iiKromium** [comment]
Smoke weed everyday

**Comment by iiKromium** [comment]
Wait

**Comment by iiKromium** [comment]
I installed the theme to my system with CHMM2...

**Comment by yellows8** [comment]
https://github.com/yellows8/3ds_homemenuhax#vuln-fix-sysupdates
