### ISSUE TITLE
Offline Themehax failure...

### ISSUE THREAD

**Issue by AlexNight** [yellows8/3ds_homemenuhax#27]
Okay, I used Ninjihax to try and install Themehax for the first time via the offline install build so that I can upgrade to 2.5 later after.  I put the folder saying, "themehax_installer" on the root of the SD card, loaded up Ninjihax to get to Homebrew, I see the themehax_installer offline v1.2 icon ready for me to choose.  It asked me if I wanted to install Home Menu themehax, clicked yes, and then it says that an error has occurred and the install failed.  Here is what it said:

Home Menu programID: 0x0004003000008f02.
Detected version: New3DS 10.2.0-28 USA
Checking for the otherapp payload on SD...
sdmc:/3ds/themehax_installer/otherapp/N3DS_U_
Error reading otherapp bin from sdmc..
Loading info from the otherapp payload...
Failed to parse the payload: 0xffffffff.
Install failed: 0xffffffff.

Can somebody tell me what I am missing as the instructions that I looked at on Yellows8's post about installing 2.5 hax on Thememenu is a bit vague?

**Comment by yellows8** [comment]
#23 

"Yellows8's post about installing 2.5 hax on" Don't know what you're talking about, perhaps you actually meant someone else.

**Comment by AlexNight** [comment]
Oh, whoops.  I meant the user named Pandaxclone on GBATemp.net. xD  I saw your name alot with this type of stuff and it stuck to my head during this "sed hep pls" post.  Anyways, I guess I'm SOL unless I use an older payload to install with?

**Comment by yellows8** [comment]
Just wait for next release, not going to help if you prefer to not wait.

**Comment by AlexNight** [comment]
Not exactly the answer I was hoping for, but oh well.  If I had known sooner about Themehax, I could've avoided this.  Thanks anyways.
