### ISSUE TITLE
Add a auto firmware spoofing  feature

### ISSUE THREAD

**Issue by ThatFluffyFox** [yellows8/3ds_homemenuhax#270]
Could you consider adding a auto firmware spoofing built in to luma so you can play CIAs that need a 9.6+ firmware without needing to do any hex editing or updating pass 9.6?

**Comment by yellows8** [comment]
"CIAs" {asking for menuhax feature that couldn't happen regardless} wat

**Comment by ThatFluffyFox** [comment]
oh sorry wrong github repository sorry
meant for luma's one

**Comment by ThatFluffyFox** [comment]
Sorry for that LMAO
