### ISSUE TITLE
Menuhax Won't Install

### ISSUE THREAD

**Issue by s3phir0th115** [yellows8/3ds_homemenuhax#31]
![img_20151030_232715](https://cloud.githubusercontent.com/assets/15504135/10861653/9b282f3e-7f5e-11e5-8ab2-52e8ae59adad.jpg)

I encounter this on a 9.0.0-20U New 3DS. I created the theme files within the menu and this is the result I seem to get consistently. I'm using Ninjahax and then starting menuhax from HBL off of that.

As a troubleshooting step I tried using the old 1.2 version, which did detect the version, but the it wasn't able to download what it needed and go from there.

**Comment by yellows8** [comment]
The README mentions ninjhax v1.x if that's what you're using......

**Comment by s3phir0th115** [comment]
Ah, indeed it does. My apologies, I'll go ahead and close it.
