### ISSUE TITLE
Can only get into Menuhax from cold boot.

### ISSUE THREAD

**Issue by Committee** [yellows8/3ds_homemenuhax#33]
In the previous version I was able to:
- Press Power Button (from any game or just the HOME Menu)
- Press HOME and hold L to boot menuhax

Now Menuhax only works from a cold boot (powered off 3DS).

I have tried type 1 or type 2 in terms of dpad triggers, tried with the boot up image and without it, tried no themes, basic color themes, and custom themes and it still only works from a cold boot.

N3DS ver 10.1

**Comment by yellows8** [comment]
Home Menu doing what it's supposed to do isn't really a "bug". With Home Menu state being proper now it only loads @ process boot it seems. So, on Old3DS you can enter another system-applet then hold the hax trigger button while returning to Home Menu(can't work on New3DS since Home Menu is still running that way)

**Comment by ghost** [comment]
So in this version you let home menu working properly ? (Not sure I understood)

**Comment by yellows8** [comment]
Exactly.

**Comment by ghost** [comment]
And... is this better ? I've one question: 3DS said me"Go to system settings to FINISH update". Aren't they trying to update automatically ? (I know it's wrong place but...)

**Comment by yellows8** [comment]
"3DS said me  ..." Not sure what you're talking about.

**Comment by ghost** [comment]
Message box in home menu.

**Comment by yellows8** [comment]
I'm not aware of any "automatic update". What did you do to trigger it?

**Comment by ghost** [comment]
Just turned on my console. Directy triggered (connected to the Internet). Afraid, I disabled SpotPass(except softaware).

**Comment by Lethaltail** [comment]
There is no automatic update. Twitter would explode right about now if there was.

@WoniMK7 You don't have to accept the update. Just ignore it.

**Comment by Lethaltail** [comment]
The 3DS will download the update no matter what, but it can't install without consent. So just ignore it and you'll be fine.

**Comment by WoniMK7** [comment]
And a think I'm almost sure: themehax is "dead" because Nintendo announced many new things and we'll have to update for sure, there isn't many people who can miss that imo.

**Comment by yellows8** [comment]
a2d28882053a294442360c661046bdec919baf4f

**Comment by Committee** [comment]
Sorry for the after comment but:

 With Home Menu state being proper now it only loads @ process boot it seems. So, on Old3DS you can enter another system-applet then hold the hax trigger button while returning to Home Menu(can't work on New3DS since Home Menu is still running that way)

When you said Home Menu state being proper now do you mean on the 10.2 firmware?

**Comment by yellows8** [comment]
On all supported system-versions, which obviously doesn't include v10.2 atm.

**Comment by Committee** [comment]
Understood.
