### ISSUE TITLE
Since 2.0 not able to boot CakesFW or rxMode sysNAND

### ISSUE THREAD

**Issue by xadox-1st** [yellows8/3ds_homemenuhax#36]
On n3DS 9.0.20E:
Since HomeMenuHax 2.0 I am not able to start sysNAND with CakesFW or rxMode.
From CtrBootManager, smeas 2.5 HBL or smashers HBL.

While using OoT3DHax with 2.5 payload I am able to enter sysNAND with CakesFW or rxMode.
So I think it has something to do with HomeMenuHax

**Comment by yellows8** [comment]
"not able to start " Is quite vague/useless........

**Comment by xadox-1st** [comment]
The n3DS reboots.

**Comment by yellows8** [comment]
I guess you mean hardware reboot. How are you telling that it's not booting into modded-firm-mode?

**Comment by profi200** [comment]
menuhax is not made for this kind of use case so if it fails ask the CFW devs. menuhax 2.0 did not block or break anything which was not already broken or shoddy coding.

**Comment by xadox-1st** [comment]
Since MenuHax is starting again and starts then CtrBootManager again.
So I can not enter sysNAND.

**Comment by yellows8** [comment]
That should be expected behaviour with "sysNAND" and "auto-boot"...

**Comment by xadox-1st** [comment]
Ok. So after starting sysNAND I have to hold the not AutoBoot key.
I will give a try.

**Comment by xadox-1st** [comment]
Working. So problem solved. Thx!
