### ISSUE TITLE
Old 3DS (JPN Ver) trying to use Menuhax 2.0

### ISSUE THREAD

**Issue by intocake** [yellows8/3ds_homemenuhax#38]
Trying to run the latest version of Menuhax on a Japanese 3DS with Firmware version 10.2.0-28J and get the follow error:

![unnamed](https://cloud.githubusercontent.com/assets/6707020/10887307/c7947ae2-81c9-11e5-8e69-860e2dc91d47.jpg)

I deleted the old themehax folder and included the newest menuhax folder.

**Comment by yellows8** [comment]
You really can't read can you?

**Comment by intocake** [comment]
I can read what it says. But I was under the impression that the your latest version (which I downloaded) worked on the newest firmware. I'm I missing something?

**Comment by yellows8** [comment]
Obviously not, hence the displayed text, README, and release-archive notes.

**Comment by intocake** [comment]
I read that. I'm not the most savvy coder, so I think I mistook a few things. I read a tweet by smea saying you fixed the menuhax for 2.0 I assumed that meant 10. "2.0" . So sorry about the confusion. So I just tried it (admittedly skimming over the read me). And then posted this.

I don't see why you have to be rude about it. But I still applaud you for your work. Good stuff and much appreciated.

**Comment by yellows8** [comment]
"rude" Not really intended, but the message displayed by the app is quite clear.....

**Comment by intocake** [comment]
You're 100% right that it's clear. But I thought I had the wrong files or something because I was under the impression it was going to work on the newest firmware. I guess I read it wrong. Anyway, I won't bore you with the details. I know the feeling about people not reading documentation so I can understand your sentiment. Wish you the best.
