### ISSUE TITLE
Reducing delay to 1.5s seems to improve boot rate?

### ISSUE THREAD

**Issue by thiagokokada** [yellows8/3ds_homemenuhax#40]
`Right before it jumps to executing the loaded ropbin, this delays 3-seconds.`

So since updating my O3DS to menuhax 2.5 I seem to get worse boot rates than before (I was using the >1.2 commits, that allowed themehax autobooting and trigger selection). Someone in GBAtemp said that reducing the above cited delay to 1.5s seems to help. I did the test (nothing scientific though):
- 3s: somewhat of 50% of boot chance (yellow screen in the majority of cases, sometimes a black screen).
- 1.5s: I was turning on my 3DS, booting HBL, pressing start, rebooting, multiple times (more than 20). Had only one failure (yellow screen).

I have a O3DS in firmware 9.2.0-20U.

**Comment by yellows8** [comment]
Not sure if changing that would really improve payload booting for _all_ systems tbh(and I'm aware that someone else tried with a 1.5s delay too).

**Comment by thiagokokada** [comment]
Can we have an option to set this delay in menuhax_manager?

**Comment by yellows8** [comment]
Ugh..... Not now.

**Comment by thiagokokada** [comment]
There is no need to do it now, this is more like a feature request for the next version or something (for now, I can use my customized version btw).

**Comment by yellows8** [comment]
5aa95aedbac81498ebf96e14983913d786252f58
1563ed332d82bbd2ce4dead71c09f84b5cdb149c
