### ISSUE TITLE
Changed sdcard

### ISSUE THREAD

**Issue by SylasMc** [yellows8/3ds_homemenuhax#42]
So i switched to a new sdcard and now the hax wont work. When I try to uninstall i get the error in the image. 
![img_20151106_094903](https://cloud.githubusercontent.com/assets/1694640/11004285/2fecf3c2-846c-11e5-88a0-53ed8e83b915.jpg)

**Comment by yellows8** [comment]
Ignore that, it's normal if you never enter Home Menu theme-settings after installing menuhax v2.0.

**Comment by SylasMc** [comment]
Ok. So after i reinstall the hax still aren't working. Booting seems to take forever now.

**Comment by yellows8** [comment]
So holding the PAD-trigger button doesn't do anything during hard-boot?

**Comment by SylasMc** [comment]
Nothing at all. I tried setting it to right on the dpad but nothing happens. Just takes forever to boot.

**Comment by yellows8** [comment]
What happens if you remove pad-cfg?

**Comment by SylasMc** [comment]
Nothing. And i timed my boot, 25 seconds.

**Comment by yellows8** [comment]
Try formatting your SD FS?

**Comment by SylasMc** [comment]
Ill try that.

**Comment by SylasMc** [comment]
That worked. Thanks!
