### ISSUE TITLE
Error code 0xc8804470

### ISSUE THREAD

**Issue by yuanwenbin36** [yellows8/3ds_homemenuhax#43]
I've met this error code everytime when I try to install menuhax, Any method to solve that?
![img_2423](https://cloud.githubusercontent.com/assets/15710468/11018292/41fa16a0-8591-11e5-9f5e-4b5b2d198b48.JPG)

**Comment by yuanwenbin36** [comment]
It's a new 3ds JP version 9.9.0.26J

**Comment by nfabia90** [comment]
I'm in the same boat as you are I'm just a user.

**Comment by yellows8** [comment]
https://github.com/yellows8/3ds_homemenuhax#installation "If you haven't already done so before, you may have to enter the Home Menu theme-settings so that Home Menu can create the theme extdata, prior to installing menuhax."

**Comment by UDK450** [comment]
I here have the same issue! And have entered theme-settings and also deleted extdata and did it again.

**Comment by yellows8** [comment]
This error means the extdata doesn't exist at all, so...

**Comment by UDK450** [comment]
But checking myself, I had it in both folders. I just deleted extdata in both folders, so we'll see how this goes after regenerating them.

**Comment by UDK450** [comment]
I've been having issues launching the modified Homemenuhax via HBL launcher when launched via the browser. It launches fine through Cubic Ninja. Does it not work properly when launched through Cubic Ninja?

**Comment by yellows8** [comment]
"modified Homemenuhax" ?
"launched via the browser" ?
"launched through Cubic Ninja" ?

Are you referring to menuhax_manager perhaps?

**Comment by UDK450** [comment]
Are the two different? Regardless, it is working just fine now... Dunno what changed.
