### ISSUE TITLE
Error code:  0xd8e06406

### ISSUE THREAD

**Issue by fischman01** [yellows8/3ds_homemenuhax#44]
I've met this error code everytime when I try to install menuhax, Any method to solve that

**Comment by yellows8** [comment]
Upload a screenshot.

**Comment by nfabia90** [comment]
Could you please teach me how to install Oot3dhax because I had trouble installing it I'm on version 10.3.0-28 U and I'm used to using tubehax was so much

**Comment by nfabia90** [comment]
Could you please teach me how to install Oot3dhax because I had trouble installing it I'm on version 10.3.0-28 U and I'm used to using tubehax was so much easier .

**Comment by yellows8** [comment]
.... So you were try to install menuhax on v10.3?

"Oot3dhax because I had trouble installing it " Be more specific.

**Comment by fischman01** [comment]
Here is the screenshot.
![img_20151116_090512](https://cloud.githubusercontent.com/assets/15844037/11176873/75528f44-8c41-11e5-8d00-a3ba290fd9f9.jpg)

**Comment by yellows8** [comment]
1) What haxx / version(if it's not, you know, what's described in the error message)?
2) What system-version?

"Here is the screenshot" {actual image is a picture from a camera} ....

**Comment by fischman01** [comment]
1) menuhax_v2.0
2) System-Version 9.2.0-12E

**Comment by yellows8** [comment]
So you're running the app via menuhax?

**Comment by doofus9341** [comment]
What he's asking is are you trying to install this with ninjhax 1.1b or hax 2.5? I had a similar issue and switched over to hax 2.5 and it installed correctly.

**Comment by fischman01** [comment]
I'm running the App with ninjhax. 
Were can i find the hat 2.5?

**Comment by yellows8** [comment]
https://smealum.github.io/ninjhax2/

**Comment by fischman01** [comment]
Perfekt! It's running! Thank's
