### ISSUE TITLE
Cannot access Eshop

### ISSUE THREAD

**Issue by Matt1412** [yellows8/3ds_homemenuhax#47]
I am able to open Homebrew launcher but get the following message when i enter eshop through the Homebrew launcher:

Device:
New 3DS US Home Designer Bundle

Device FW 
10.1.0-27U

Error Code:
022-2511

In order to use online services, a system update is required. 

Go to System Settings to perform a system update.

I installed the latest Homebrew starter kit from:
http://smealum.github.io/3ds/

**Comment by yellows8** [comment]
This has nothing to do with menuhax.

http://3dbrew.org/wiki/10.3.0-28#Server-side_NNID_NVer_update
