### ISSUE TITLE
Failed to open extdataID=0x000002cd , error 0xc8804464

### ISSUE THREAD

**Issue by ciarre** [yellows8/3ds_homemenuhax#48]
![4575ae5b99dce59d5ba256ece7f05b3a](https://cloud.githubusercontent.com/assets/16053890/11449629/88be3704-9542-11e5-855c-97afa666f72c.png)
So I'm using browserhax to get to the homebrew launcher and this happened. I'd really appreciate some help...

**Comment by yellows8** [comment]
Did you do what the app instructed there?

**Comment by raphauell0** [comment]
I'm having the same problem, can be solved?

**Comment by Maxakator** [comment]
somebody
 knows how can be solved??

**Comment by YodaDaCoda** [comment]
Did you read what it says?

**Comment by ghost** [comment]
I do not have a Home Menu theme-settings option in the homebrew menu.

**Comment by ihaveamac** [comment]
you're supposed to go to the 3DS home menu and tap the icon in the top left. then tap "Change Theme" and it will create the theme extdata. then you can install menuhax.

**Comment by burnout293** [comment]
It Worth ihaveamac =D Thank you !
