### ISSUE TITLE
Install failed: 0xd900182f

### ISSUE THREAD

**Issue by Mythrandir** [yellows8/3ds_homemenuhax#49]
Using Home Menu programID: 0x0004003000008f02
Failed to get the Home Menu title-version: 0xd900182f
Install failed: 0xd900182f

Console: Nintendo New 3DS XL (Majora's Mask Edition)
Home Menu: Ver. 9.0.0-20U

![1209011023](https://cloud.githubusercontent.com/assets/16219918/11679116/a6e9d98e-9e13-11e5-9de9-dc9404c4f97b.jpg)

**Comment by yellows8** [comment]
https://github.com/yellows8/3ds_homemenuhax#installation
"Due to AM access being required with >v1.2, this app is not usable with regular ninjhax v1.x without additional hax."

**Comment by Mythrandir** [comment]
So I somehow managed to install Ninjhax < 2.0?

**Comment by yellows8** [comment]
If you didn't use the QRCode _directly_ from here, yes: https://smealum.github.io/3ds/

**Comment by Mythrandir** [comment]
Thank you. I thought I had, but I'll just perform another fresh install.

**Comment by Mythrandir** [comment]
After performing a fresh install, MenuHax was successfully installed. Apparently I did use an outdated QR code. Thanks again.

**Comment by yellows8** [comment]
You're welcome.
