### ISSUE TITLE
Way to change button trigger?

### ISSUE THREAD

**Issue by HeroLarcio** [yellows8/3ds_homemenuhax#5]
It'd be nice if the installer had an option to choose which button you hold triggers homebrew, because my L button isn't working well.

**Comment by yellows8** [comment]
That's rather difficult: the compression is done in python currently. Not interested in loading something from SD for that either currently.

For now you have to build it yourself.

**Comment by yellows8** [comment]
This could be done with additional ROP probably, but this is not a bug therefore it has lower priority than the other github issues here.

**Comment by ghost** [comment]
One simple solution would be checking if any button is held. It wouldn't cause issues as there really aren't any other reasons to hold buttons during start up, and it would resolve any console-specific button issues.

**Comment by s0r00t** [comment]
+1 for the "check if any button is held".
The L&R buttons on my 3DS are broken (thanks a lot StreetPass Plaza), and I'd like to switch from ironhax to themehax.

**Comment by yellows8** [comment]
I would prefer to not have it boot the payload by default.

**Comment by ghost** [comment]
That isn't booting the payload by default. It would still only boot on button press, but it would be any button instead of just L, as some people have broken buttons.

**Comment by yellows8** [comment]
Oh oops... "checking if any button is held" Was thinking of the USE_PADCHECK value you mentioned using elsewhere.

**Comment by RikuKawai** [comment]
Would it be possible to switch the buttons so that it boots by default, and holding a button makes it go to the home menu? This would be really nice for CFW users because they could autoboot.

**Comment by Hartie95** [comment]
You would still need to press the button once, to stop booting in The cfw, or it will be an infinite loop/ it crashes.

**Comment by RikuKawai** [comment]
Actually there is an autobooting version, and I'm using it to boot rxMode EmuNAND. People still use SysNAND CFW?

**Comment by yellows8** [comment]
2fe72bbbb236604f35099292043fe4b7c31e7667 2b2c689422519ce6425e95c642192f4c2ee8e3fb
