### ISSUE TITLE
Wont reboot to home menu on the launcher after installing MenuHax. Never launches Home menu unless MenuHax is uninstalled

### ISSUE THREAD

**Issue by mrdreemurr** [yellows8/3ds_homemenuhax#51]
I've installed MenuHax a month ago and just installed MenuHax a month later (Now), to see if this issue for me have been fixed. I've still been having this problem. As such as the yellow screen in the other issue post. Any help on fixing this?

**Comment by yellows8** [comment]
This is menuhax v2.0 with latest payload right? What pad-config are you using?

**Comment by mrdreemurr** [comment]
Yep. after making my own custom one it just keeps launching it. I just want
to have A, A, B, B, as my pad config.

**Comment by yellows8** [comment]
What system-version?

**Comment by mrdreemurr** [comment]
9.9.28 I think, (Its the one that you cant use the first browser hax link
and it was patched for the version)

**Comment by yellows8** [comment]
"after making my own custom one it just keeps launching it." ... So you're having this issue because you _modified_ the payload? What _exactly_ did you change?

**Comment by mrdreemurr** [comment]
Like I mean the custom buttons to press to launch it

**Comment by yellows8** [comment]
If you're still having trouble you can re-open this if you comment with more details.
