### ISSUE TITLE
custome theme BGM install fails

### ISSUE THREAD

**Issue by GizmoTheGreen** [yellows8/3ds_homemenuhax#52]
![scr_1_top_left](https://cloud.githubusercontent.com/assets/1146558/12013820/942ff540-ad62-11e5-8403-27cff6527b98.png)

rest of the theme installed and works fine though, it's just... a bit dead since there is no BGM...
this is an actual theme I bought and extracted with homemenu_extdata_tool

**Comment by yellows8** [comment]
... You do know about screenshots, right?

The theme Home Menu was using prior to running menuhax_manager must not be using BGM, hence that error.

**Comment by GizmoTheGreen** [comment]
I do know about screenshots, but this was faster.
I have changed out the photo with a proper screenshot.
I'm using the same theme I'm trying to install (just with menuhax)

steps as of now:
1. select my bought theme
2. extract it with homemenu_extdata_tool
3. rename files from bodycache.bin and bgmcache.bin to body_LZ.bin and bgm.bcstm respectively. and move them to menuhax_manager folder.
4. start menuhax_manager and select install custom theme.

**Comment by yellows8** [comment]
Home Menu must be using the default BGM when you try installing custom-themes in general(not just with menuhax_manager).

Why are you doing this with a DLC-theme? Is it because you're on >=v10.2 and only have one DLC-theme?

**Comment by GizmoTheGreen** [comment]
It's the theme I always use. Squid sisters. 
10.3 JP console. 

Well if it's not supposed to work? then it's fine I guess

**Comment by yellows8** [comment]
e9b18161a2f2c8fc9d799f86de896a5dd42ac41c
