### ISSUE TITLE
[shufflehax] Cannot run boot.3dsx when pressing HOME in game booted with RegionFour

### ISSUE THREAD

**Issue by RocketRobz** [yellows8/3ds_homemenuhax#54]
When pressing HOME button in game booted with RegionFour to return to HBL, it gets stuck in a yellow screen. I think the problem only occurs in shufflehax. My N3DS is 10.3 U.

**Comment by yellows8** [comment]
Forgot about this issue I guess.

I'm not sure what "RegionFour" you actually mean(region-free entry from hbmenu perhaps?), but either way you're not really supposed to press HOME button for exiting the game anyway.
