### ISSUE TITLE
MenuHax doesn't load when Badges are being used

### ISSUE THREAD

**Issue by Darky2k1** [yellows8/3ds_homemenuhax#55]
Not sure if this is a bug or working as designed. When I have badges on my screen MenuHax doesn't work. It freezes with a white screen on the bottom. Once I remove the badges everything works perfect.

**Comment by yellows8** [comment]
How many times did you try it?

**Comment by Darky2k1** [comment]
I have repeated it around 10 times - Each time it does the same thing - Only freezes when Badges are on the screen - doesn't freeze when they are all removed

**Comment by yellows8** [comment]
That's one of those weird issues with *hax payload + menuhax. No idea what causes those issues, of course.

**Comment by yellows8** [comment]
@darkunderdog How many badges are you using?

**Comment by ghost** [comment]
Works fine for me on N3DS 10.3. Even added a bunch of extra badges to my home screen to make sure.

**Comment by Darky2k1** [comment]
Came back today to test it again. Launched it 5 times in a row with badges on the screen instead of alternating like I have done in the past - This time it booted 2 out of the 5 times to the homebrew menu. So I guess its just hit or miss... Guess we can close this - @yellows8 I had just 3 badges on the screen though 950 in the library
