### ISSUE TITLE
Ironhax and Menuhax won't download with browserhax

### ISSUE THREAD

**Issue by Sheng137** [yellows8/3ds_homemenuhax#56]

**Comment by yellows8** [comment]
........... This is the completely wrong repo. "won't download" ?

**Comment by Lethaltail** [comment]
They probably think that the starter kit gets downloaded. We won't know until they decide to explain themselves.

**Comment by Sheng137** [comment]
Sorry my english sucks .-. But I tried to say that I can't install ironhax or menuhax with browserhax... When I tried to install ironhax it says "looks like something went wrong" and when I tried to install menuhax it says "failed to initialize HTTPC: 0xd8e06406" and then it gives me an explination and then the url of this website
