### ISSUE TITLE
Crash when exit SSB4 to home menu

### ISSUE THREAD

**Issue by cynosura15** [yellows8/3ds_homemenuhax#57]
When I press home menu button when playing SSB4, it crash (game freeze). The only way to exit is to press power button, or remove the SD card/game card.

**Comment by ihaveamac** [comment]
this looks the same as #13

**Comment by cynosura15** [comment]
Note that I'm on old 3ds 9.9 with latest menuhax installed.

**Comment by cynosura15** [comment]
Oh okay.
