### ISSUE TITLE
Error while trying to install 

### ISSUE THREAD

**Issue by DarkLordRS** [yellows8/3ds_homemenuhax#59]
I seem to be unable to install this at all. No matter what settings or whose files I use - even those of someone who got it to work successfully with o3ds 10.3, what I'm running - it always gives the following when I attempt to install.

http://prntscr.com/9l2a3t

Shit pic, but the best I can give, apologies. It says 'Install failed: 0xc82044b4" in case that's hard to see.

**Comment by yellows8** [comment]
"the best I can give" _cough_ hax payload screenshots _cough_.

Verify that you aren't running low on SD card free space.

**Comment by DarkLordRS** [comment]
..okay, turns out I'm a dumb dumb, completely forgot that you could take screenshots.

I had a Hans s4 rom, the entirety of PM CC and my nintendo 3ds folder on my sd card, deleted s4 and it didn't work. gonna delete PM CC to see if it helps. 

Edit: Freed up further space, didn't help. Ouch.

**Comment by DarkLordRS** [comment]
booped in case edits dont notify, i don't use github lmao

**Comment by yellows8** [comment]
Goto System Settings Data Management for extdata, then delete the theme-cache extdata. Enter the Home Menu theme-settings menu so that the extdata is created, then try menuhax installation again.

**Comment by DarkLordRS** [comment]
There.. isn't any theme-cache extdata, seemingly. Not listed under Data Management -> Extra Data. Should I delete it manually using the hmh installer, or does that not work?

Edit: deleting using the hmh installer gives the same error as trying to install menuhax. This is weird.

**Comment by yellows8** [comment]
I guess you could try, but it won't _completely_ delete the entire extdata.

**Comment by DarkLordRS** [comment]
Deleted extdata manually with 3dbrew's info on where it's located, made the data using the theme settings and got it installed! Thanks yo!

Keep doing the work you're doing man, you're literally a god to the community.

**Comment by yellows8** [comment]
"you're literally a ..." ugh.
