### ISSUE TITLE
"Failed to download the actual payload with HTTP" (error picture inside)

### ISSUE THREAD

**Issue by eicoolguy6** [yellows8/3ds_homemenuhax#60]
![img_0301](https://cloud.githubusercontent.com/assets/6549398/12075422/5b765baa-b14e-11e5-9f20-5206a53c463a.JPG)

**Comment by yellows8** [comment]
Please don't report HTTP-related issues unless you attempted install multiple times.

https://3dbrew.org/wiki/HTTP_Services#Error_codes

**Comment by eicoolguy6** [comment]
I have tried multiple times, and on different networks.

**Comment by eicoolguy6** [comment]
Oh. It just worked for some reason. Thanks for the speedy reply, though!
