### ISSUE TITLE
Fails with red bottom screen

### ISSUE THREAD

**Issue by gingerbeardman** [yellows8/3ds_homemenuhax#61]
To reproduce I do this: 
- Switch on the N3DS
- Hold L until
- Homebrew Launcher starts (\* see below)
- Choose any 3dsx executable ([CTRxplorer](https://gbatemp.net/threads/release-ctrxplorer-open-source-sd-file-manager.390353/) and [RetroArch](http://buildbot.libretro.com/nightly/nintendo/3ds/) are my test apps)
- Observe result

[smea's starter pack launcher](http://smealum.github.io/3ds/)
Fails at red bottom screen launching any 3dsx

for contrast:
[suloku's launcher with sorting and folders](https://gbatemp.net/threads/homebrew-launcher-with-sorting-and-folder-support.396793/)
Fails at red bottom screen launching any 3dsx

[mashers launcher with grid layout](https://gbatemp.net/threads/release-homebrew-launcher-with-grid-layout.397527/)
Always works launching any 3dsx

FOR ALL
Always reproducible on every boot for me.

My setup...
- N3DS running 10.1.0-27E
- HomeMenuHax 2.1
- Default theme (none)
- starter-kit 29th Dec
- hax payload 2nd Jan

Video
http://cl.ly/1p42251b1j0h

**Comment by gingerbeardman** [comment]
Added Video link above

**Comment by yellows8** [comment]
Did you try with homebrew apps included with the starter-kit?

**Comment by gingerbeardman** [comment]
I do not have them all installed, but here are the results with what i do still have:

CHMM2 - fails, red screen

HANS - works, green screen

menuhax_manager - works, dark red screen
scrtool - works, dark red screen
ftbrony - works, dark red screen

let me know if there's a missing app you'd like me to try.

**Comment by yellows8** [comment]
I'm not sure why you're saying "works" then {colored-screen} tbh.

EDIT: Also, non-3ds_hb_menu boot.3dsx is not supported here, if you must use those goto the appropriate github repo for it.

**Comment by gingerbeardman** [comment]
I always thought that the colour screen was an indicator of some sort? if not I'll remain from mentioning it.

3ds_hb_menu boot.3dsx fails, which is why I'm here. The other loaders were just to show that one other loader always works.

Happy New Year, BTW

**Comment by yellows8** [comment]
Latest *hax payload and latest starter-kit?

**Comment by gingerbeardman** [comment]
Yes, latest on both.

Payload from today (I ran menuhax manager to update hax)
Starter kit files I downloaded on 29 December, after the most recent update.

**Comment by yellows8** [comment]
If this is still an issue even after formatting your SD FS, you can re-open this.
