### ISSUE TITLE
won't install

### ISSUE THREAD

**Issue by Reual4412** [yellows8/3ds_homemenuhax#63]
I did all the steps and nothing is working.

what it says 

"opening extdata archives 
failed to open theme extdata with extdata ID=0x000002cd retval: 0xc88004464"

and I have done the  all the steps

**Comment by Reual4412** [comment]
it has change my problem it still doesn't work (i deleted all data and retried) 

"... Invalid http content size 0x0000a478. failed to download actual payload with HTTP:0xffffffffd.
install failed:0xffffffffd."

**Comment by yellows8** [comment]
ONLY use the latest release-archive ....
