### ISSUE TITLE
Will not let me install menuhax

### ISSUE THREAD

**Issue by capitanveneno** [yellows8/3ds_homemenuhax#65]
Every time I try to install the hax menu I get the message: failed to open theme Exdata With exdataID = 0X000002ce , retval : 0xc8804464 Exit this app , then a goto home menu Exdata theme . an error ocurred . please help.

**Comment by capitanveneno** [comment]
![img_20160104_201921](https://cloud.githubusercontent.com/assets/16545983/12098699/2c077eda-b324-11e5-9556-19d83717b428.jpg)

**Comment by yellows8** [comment]
Why can't you do what it already told you to do?

..............

**Comment by capitanveneno** [comment]
I'm sorry but I do not quite understand Spanish and English. Does he should do ? I think I did everything but I see no. what should I do? I'm desperate. I do not know what to do.

**Comment by clementguerin1** [comment]
just for help when u see this error return to home menu of your 3ds and go to home menu settings to change theme menu then ur 3ds while create the data theme after retry to install menuhax i thinks it is work sorry for my bad english i ma french so if you are french i can explain you in french 

byey guy

**Comment by clementguerin1** [comment]
I test this solution for my O3DS and it works so try it ^^
