### ISSUE TITLE
HomemenuHax crashing when booting

### ISSUE THREAD

**Issue by karynyukizawa** [yellows8/3ds_homemenuhax#66]
Hey guys, I've installed the HomemenuHax and...

https://i.imgur.com/2j1wrcQ.jpg

This is what happens when I try to boot. I know that I should happen then boot but...
It freezes right there. No HBL, nothing.

I'm using a 9.2 sysNAND, just formated the SD card and made the theme profile before installing.

**Comment by yellows8** [comment]
1) What menuhax version?
2) Is this v9.2 system the result of a downgrade?

**Comment by karynyukizawa** [comment]
1) Menuhax 2.1
2) Yes, it was downgraded.

**Comment by yellows8** [comment]
So the *hax payload works fine from other hax on your downgraded system?

**Comment by karynyukizawa** [comment]
When I installed the menuhax, it created a ropbin (probably downloaded).
But when I use browserhax, the *hax payload works fine.

**Comment by karynyukizawa** [comment]
Yellow, any solution for my problem? I really want to use Menuhax :(
Should I try to "delete" the 3ds folder (I mean, backup it on my pc and delete from my SD card) and retry to install Menuhax with a clean 3ds folder (since I used my old 3ds folder that I had before downgrading)?

**Comment by karynyukizawa** [comment]
Yellow, one thing that I noticed:

It's installing Shufflehax instead of Themehax (at least it says that is installing Shufflehax's files and it appears as shufflehax when I uninstall)
Maybe that's causing the crashes since 9.2 doesn't have Shuffle Theme option.

**Comment by yellows8** [comment]
It's impossible for it to successfully install shufflehax on <v10.2 since the release-archive doesn't include the required theme-data for that.

**Comment by karynyukizawa** [comment]
Probably the hax is getting the info on emuNAND, not on the sysNAND.
My emuNAND is on 10.3.

I can record a video if you want to check more details about what is happening.

**Comment by yellows8** [comment]
Nandredir doesn't matter unless that's what you're running the app under.

**Comment by karynyukizawa** [comment]
Found out the problem.

The homemenuhax payload (the one that downloads) was the one causing the problem.
