### ISSUE TITLE
[Feature Request] Multiple homebrew

### ISSUE THREAD

**Issue by BlackLotus** [yellows8/3ds_homemenuhax#67]
Right now you can load boot.3dx or you can boot the normal firmware.
I use homemenuhax to autoload rxtools and if I press L I boot the default firmware.
An option to specify a secnd different boot file boot2.3dx or something would be great and I could start the homebrew menu with L and the vanilla system with R.

**Comment by yellows8** [comment]
Just use one of those "boot-managers" if you _really_ have to.

**Comment by BlackLotus** [comment]
Somehow missed that answer.
It's not that I don't know of the "boot loaders" it's just that I find them ... clunky.
There are many reasons why it's suboptimal to use those not only that they can be unreliable, but also that behaviours that result from using them occur that I personally dislike. Who wants to be put back to a "boot loader" every time you close an application?
It would be a cleaner approach to have a choice in menuhax, even thought I understand why you would say that using a workaround like this would be the solution for me.
If I were to write the feature myself would you likely include it into menuhax or would I be wasting my time?

**Comment by yellows8** [comment]
I really don't want to implement this in ROP.

**Comment by BlackLotus** [comment]
OK understood.tbh I normally want a clean cut codebase as well
