### ISSUE TITLE
Menuhax conflicts with Browserhax

### ISSUE THREAD

**Issue by ghost** [yellows8/3ds_homemenuhax#72]
When I have a custom theme installed via menuhax, I cannot run homebrew through browserhax.
This only happens when a custom theme is installed.
Ironhax works fine.  i don't know about any other kinds of hax.
I have a New 3DS XL version 10.3.0-28U.

**Comment by yellows8** [comment]
... Why are you using browserhax when you have menuhax installed?

**Comment by ghost** [comment]
Just is case I want to launch homebrew from the 3DS home menu without turning my 3DS off and on again...
It's only a small technical issue.

**Comment by s0r00t** [comment]
You can just use other entrypoints, such as ironhax or hb_loader (if on CFW/able to install CIAs).

**Comment by yellows8** [comment]
yellows8/3ds_browserhax_common/issues/37
