### ISSUE TITLE
Error Code: 0xd900182f ... Install failed

### ISSUE THREAD

**Issue by MartinDaDon** [yellows8/3ds_homemenuhax#74]
so i downgraded my new3ds xl from 10.2 to 9.2, after that menuhax didn't work.
now i tried to install it again and this error code appears. can anybody help?

![wqs 26dw](https://cloud.githubusercontent.com/assets/16723448/12360337/a61af166-bbb7-11e5-9d38-e470fb23cfee.jpg)

**Comment by MartinDaDon** [comment]
ok, solved it. for everyone with the same problem, do not use ninjhax to boot homebrew launcher, use browserhax

**Comment by JAWSxs** [comment]
is that what it is?  omg I've been going crazy.  but I've been using cubic ninja to boot because I can never get browserhax to work.   edit first time I just tried Browserhax it works.  you are right...ninjhax didn't work

**Comment by yellows8** [comment]
This is described in the README for ninjhax v1.x ...................

**Comment by JAWSxs** [comment]
sorry yellow It's the first time I've ever had to use menuhax.  only used cubic ninja before.  but anyways it worked perfect when I went back and tried today.  

Thanks again for your work!!!
