### ISSUE TITLE
Error 0xd8a0a046

### ISSUE THREAD

**Issue by ghost** [yellows8/3ds_homemenuhax#75]
![20160116_172132 1](https://cloud.githubusercontent.com/assets/16278765/12375400/ca2168a6-bc75-11e5-9beb-b9494d8dc396.jpg)
What can I do to fix this error?

**Comment by yellows8** [comment]
https://3dbrew.org/wiki/HTTP_Services#Error_codes

**Comment by brindlejustice** [comment]
I also ran into this problem. My internet connection is perfectly fine, Anything I can do?

**Comment by yellows8** [comment]
Don't know if it's server-side DNS related however...
