### ISSUE TITLE
web browser 

### ISSUE THREAD

**Issue by sasuke116** [yellows8/3ds_homemenuhax#76]
web browser these fallen and can not access the downgrade there will be some way to enter the homebrew?

**Comment by yellows8** [comment]
No idea what you're talking about. This is the wrong repo to report browserhax issues. Go elsewhere for downgrade support.

**Comment by sasuke116** [comment]
sorry I mean the browsehax since direcion http://yls8.mtheall.com/3dsbrowserhax.php is not working and I thought it was here that these errors can not be so where were published I ask why ?

**Comment by yellows8** [comment]
Still don't know what you're talking about, "not working" is useless.

EDIT: Not sure if you're referring to server-side DNS issues or something else.
