### ISSUE TITLE
Impossible to create a custom main-screen from PNG

### ISSUE THREAD

**Issue by tomcraft** [yellows8/3ds_homemenuhax#77]
The error says "Failed to get the filesize of the SD PNG: 0x00000002." when select "Configure menuhax main-screen image display"

**Comment by yellows8** [comment]
README

**Comment by tomcraft** [comment]
Big thanks guys for your help and for your awesome stuff !! :D

2016-01-25 20:14 GMT+01:00 yellows8 notifications@github.com:
