### ISSUE TITLE
[Question] How would one modify menuhax to load a different 3dsx file?

### ISSUE THREAD

**Issue by ghost** [yellows8/3ds_homemenuhax#78]
I'm looking into a more efficient way than ctrbootmanager to autoboot my EmuNAND with cakes fw. I don't want to completely replace boot.3dsx with the cakes fw loader becuase I still want to use for example hblauncher_loader

**Comment by yellows8** [comment]
This does not belong in menuhax(_manger). #67

**Comment by ghost** [comment]
Ok
