### ISSUE TITLE
Can't build on arch linux

### ISSUE THREAD

**Issue by ghost** [yellows8/3ds_homemenuhax#79]
```
# make defaultbuild
make: *** No rule to make target 'defaultbuild'.  Stop.
```

I have base-devel installed, and devkitarm + the devkitarm variable set up

**Comment by yellows8** [comment]
Are you really running make under "3ds_homemenuhax/", not "3ds_homemenuhax/menuhax_manager/"?

**Comment by ghost** [comment]
Just tried again and made sure,

```
# make defaultbuild
Makefile:144: Makefile_modules_include: No such file or directory
make: *** No rule to make target 'Makefile_modules_include'.  Stop.
```

**Comment by yellows8** [comment]
https://github.com/yellows8/3ds_homemenuhax#building "Before building menuhax(_manager), you must run setup_modules.sh at least once. ..."

**Comment by ghost** [comment]
oh... oops
