### ISSUE TITLE
KOR Support

### ISSUE THREAD

**Issue by Committee** [yellows8/3ds_homemenuhax#8]
Noticed KOR 3DS not getting any love, anything I could do/submit to get KOR region supported?

**Comment by yellows8** [comment]
Not much point bothering with KOR/CHN/TWN in the release-archive since the hblauncher payload doesn't support those regions either.

**Comment by smealum** [comment]
that's a good point actually. the reason those are not supported by my
payloads is because cubicnin, ironfall and youtube (i think) dont exist in
those regions.

but i guess if we do have entrypoints that work there i could try and make
my payloads work there too.

**Comment by Committee** [comment]
Well yes cubicnin, ironfall and youtube.

However it has the browser that comes with the firmware, possible that can be used as the main entrypoint?

**Comment by smealum** [comment]
"but i guess if we do have entrypoints that work there i could try and make
my payloads work there too."

that's what i meant. now that we do have entrypoints that work in those
regions i'll see what i can do about adding support to the main payload.

**Comment by Committee** [comment]
Sorry Herbal Tea making me woozy.

Region-free is what we're mainly looking for since not a lot of titles came out in the KOR region.

Many thanks.

**Comment by yellows8** [comment]
7e7a1ad79298dfb6dd7ac75a5b268e8841d53bf0

This issue will be left open until the hblauncher-payload actually support KOR(the installer isn't completely usable with KOR otherwise).

**Comment by metrojoa** [comment]
Are there any advancements in  creating a hblauncher-payload that supports KOR? Also what do you mean here: "The initial release archive only supported USA, EUR, and JPN. The latest git also supports KOR, which should be included in the next release."

**Comment by yellows8** [comment]
"Also what do you mean here" What do you not understand?

**Comment by metrojoa** [comment]
I'm sorry English is my second language. You said in your Supported System Versions "The initial release archive only supported USA, EUR, and JPN. The latest git also supports KOR, which should be included in the next release. TWN can't be supported currently. CHN isn't supported since the last Home Menu update(v7.0) was before themes even existed in Home Menu." I was just curious what you meant here. Are you saying that even though there is no hb launcher payload existent at the moment, it would work with homemenuhax if it was every created?

**Comment by profi200** [comment]
It means KOR support comes with the next release. If you build it yourself it already supports it.

**Comment by yellows8** [comment]
Yes, latest git would be usable with latest hblauncher-payload if/when KOR is supported in the hblauncher-payload.

**Comment by metrojoa** [comment]
thanks for the reply. I really hope the payload supports KOR soon because there aren't that many 3DS games released in Korea compared to other regions and we really need it.

**Comment by sherks** [comment]
Thanks god ! Finally i found the hope . I am running 10.1.0-23K FW , if you need someone to test it for you , i will be very happy to do it ! Keep going on !

**Comment by Committee** [comment]
The latest commit already supports KOR, it is up to Smealum now I think to add support to HBL.

**Comment by sherks** [comment]
Thanks for that informations Mr @Committee  . @smealum could you please give us some details, we really want to hear from you

**Comment by metrojoa** [comment]
Help me @smealum. You're my only hope. And also all the gamers who live in Korea. You will be treated like the second coming if you succeed.

**Comment by Committee** [comment]
Still no love for KOR users? @smealum :+1:

**Comment by sherks** [comment]
Tried to contact for some infos....maybe he really busy, just wait  :D

**Comment by metrojoa** [comment]
I'm really crossing my fingers.

**Comment by metrojoa** [comment]
I'm really crossing my fingers.

**Comment by haharazer** [comment]
how about TWN?Is there any chance to support TWN?

**Comment by yellows8** [comment]
https://github.com/yellows8/3ds_homemenuhax#supported-system-versions

**Comment by Committee** [comment]
Any word if smealums payload already works with KOR?

**Comment by yellows8** [comment]
@Committee  Not supported currently.

**Comment by yellows8** [comment]
Re-opening until a new release-archive actually supports KOR due to [this](https://www.3dbrew.org/wiki/Home_Menu#Home_Menu_Themes).

**Comment by Committee** [comment]
Huh interesting did not notice that the Theme Menu was not there.

**Comment by yellows8** [comment]
I guess I'll have to disable building KOR themehax/shufflehax(see recent wiki edit).
