### ISSUE TITLE
File menuhax_USA

### ISSUE THREAD

**Issue by Zetvot** [yellows8/3ds_homemenuhax#80]
Hi! when I try to install menuhax in a version 10.4, this failed because I dont have the file: "menuhax_USA24578_new3ds.lz"   what I can do?  (I´m from Guatemala, and my english is some bad) Thanks

**Comment by yellows8** [comment]
You need to use the v2.2 archive ...

**Comment by Zetvot** [comment]
Can you give me a link for download? or some like that?

**Comment by Zetvot** [comment]
this?

Added prebuilt_menurop for v10.4. Added v10.4 version files under shufflehax_menuversions. Updated README regarding v10.4, etc. Updated some UI text in menuhax_manager. Updated the version to v2.2.

**Comment by yellows8** [comment]
.................. https://github.com/yellows8/3ds_homemenuhax/releases

**Comment by Zetvot** [comment]
thanks I was install this but now I need instal sysupdater  but this failed to geting the .cia file

**Comment by yellows8** [comment]
This is the wrong repo to be complaining about failing downgrade-related stuff(which isn't even available on your sysver).
