### ISSUE TITLE
Error 0xc8804470

### ISSUE THREAD

**Issue by aznchronos** [yellows8/3ds_homemenuhax#82]
So I've been getting an error trying to install MenuHax 2.2 on my screen and everything on the homebrew menu is booting up like it normally does, but it seems like a lot of the functions of homebrew menu is quite limited. I tried resetting it and reinstalling, factory resetting it, and still doesn't seem to make a difference. I was looking at the other threads similar to it and looks like MightyJak was having the same issues as me. Not sure what possible solutions there are or how to go about it, so if possible... help?

![5352fa2c-c077-11e5-8653-8d94b45c152d](https://cloud.githubusercontent.com/assets/1797656/12584366/6859b6e6-c404-11e5-9fe0-73f5c16ba28f.jpg)

**Comment by yellows8** [comment]
.... It clearly said that install finished successfully.

"but it seems like a lot of the functions of homebrew menu is quite limited" Huh?

**Comment by aznchronos** [comment]
Yeah. It's showing the error that it can't retrieve information and use of
homebrew menu at that point seems weird compared to normal. Some apps dont
function at all after this error. Not sure if that's exactly homemenuhax or
not though.

**Comment by yellows8** [comment]
Don't know what you're talking about.

EDIT: I don't support non-3ds_hb_menu here btw.

**Comment by kakaroto296** [comment]
Which would have the same problem the solution .. Do not open any application. It goes black when I try to open emunand9 and FBI .. What's the problem

Thanks for everything
