### ISSUE TITLE
Install failed: 0x00000002

### ISSUE THREAD

**Issue by lukegiglio** [yellows8/3ds_homemenuhax#83]
Hello,

I'm getting the following problem while trying to install menuhax:

![arsr_3vkvx9gdwvzw_f7ywmww4ekskz680nmulxlard2](https://cloud.githubusercontent.com/assets/16904160/12590358/dc4a569c-c462-11e5-88d5-8cf3ea012008.jpg)

What I've tried so far:
- Changing theme
- Selecting no theme
- Copying the files to the SD card again
- Cheching the extra data for some cache theme files (?) - haven't found anything

Can someone please help me?
Thank you very much.

**Comment by yellows8** [comment]
You're using an outdated release-archive.

**Comment by shahanshah3** [comment]
I used both menuhaxmanager 2.2 and 2.1, but it didn't work. My system is on 9.2

**Comment by yellows8** [comment]
"My system is on 9.2" {NAND system-version detected by app is v10.4} Wut. Are you trying to install menuhax under nandredir for whatever reason?

You clearly didn't extract the v2.2 archive correctly either.

**Comment by shahanshah3** [comment]
Nandredir? All I'm trying to do is set up themehax/menuhax on my 9.2 sysnand so I can easily boot into rxmode

**Comment by shahanshah3** [comment]
strange, I just tried a few more times and suddenly it worked

**Comment by lukegiglio** [comment]
I've just tried using the files of this link: https://smealum.github.io/ninjhax2/starter.zip
Have got the same error My System Version is 10.4 and I have an old Nintendo 3DSXL.
Are there any files mising?

**Comment by yellows8** [comment]
You're clearing using an outdated archive / extracted it wrong.

**Comment by lukegiglio** [comment]
Could you please give me the correct link then? I've tried with several Versions already..

**Comment by yellows8** [comment]
https://github.com/yellows8/3ds_homemenuhax/releases
