### ISSUE TITLE
Add a way to skip hax execution from external app

### ISSUE THREAD

**Issue by Cpasjuste** [yellows8/3ds_homemenuhax#85]
Hi,

This is not an issue but it may be the best place to request this. 

It would be useful to be able to reboot to homemenu from an application (CtrBootManager for instance) . For now it seems there's no way to do this if we set menuhax to "autoboot" as it will of course trigger the jump on next reboot. 

For example having the possibility to write a file to SD which will be interpreted by menuhax as "don't jump , continue to homemenu", deleting the file when doing so. Or maybe add a flag to the menuhax binary config file which would be reset when triggered. 

Not sure I'm clear as English is not my primary language...

Thanks anyway !
David.

**Comment by yellows8** [comment]
I think someone else mentioned this on IRC and I told them to create an issue so that I don't forget about it/etc, and of course that never happened.

EDIT: s/never/finally

**Comment by Cpasjuste** [comment]
It was me :x Better late than never !

**Comment by yellows8** [comment]
ae0668b08a7c243be7b2fe42bbe6611e828cdf88
https://github.com/yellows8/3ds_homemenuhax/blob/5a458faff3116221c454115b704f3f90a29785d8/menuhax_manager/source/menuhax_manager.c#L47
