### ISSUE TITLE
Menuhax conflicts with CHMM2?

### ISSUE THREAD

**Issue by RenAmbrose** [yellows8/3ds_homemenuhax#86]
So, a few days ago, I got browserhax up and working in an attempt to get some custom Smash music. I tried setting up Menuhax for ease of access, ran the install, and went to test it. I got it to work while exiting the friends list, and installed a custom theme from the Custom Home Menu Manager 2 made by Rinnegatamante; included in the homebrew starter kit. From that point on, I haven't been able to get Menuhax to work at all, and browserhax is unstable enough on old3DS that I've been unable to troubleshoot anything. Been running 10.4, not sure if that's important or not. Anyways, the question I'm trying to ask is, do custom themes conflict with Menuhax at all?

**Comment by yellows8** [comment]
https://github.com/yellows8/3ds_homemenuhax#themes "... As a result, other custom-theme installation tools will not be compatible with installing to these seperate files, without an update for them to support this. Using those tools without being updated for this, will result in menuhax being overwritten with the custom-theme."

Don't know if CHMM2 was ever updated for that yet or not.

**Comment by RenAmbrose** [comment]
Ahh, okay. Must have missed that bit. Guess I'll hold off on the themes till a workaround for that is found.

**Comment by ihaveamac** [comment]
I just want to add that CHMM2 2.5 should now detect menuhax and install themes properly to not overwrite it. as far as I know, the starter pack was not updated with this new version yet.

**Comment by RenAmbrose** [comment]
Good to know, I'll replace the starter one with the current one

**Comment by ghost** [comment]
https://gbatemp.net/threads/tinker-shuffle-menuhax-theme-manager.407445/
Here's a custom theme installer that's compatible with menuhax.  Of course, it does not allow shuffling.
