### ISSUE TITLE
Menuhaxx manager won't build

### ISSUE THREAD

**Issue by mariogamer2** [yellows8/3ds_homemenuhax#87]
Always give me this on ubuntu 15.04:

http://pastebin.com/PsTmXhWW

**Comment by yellows8** [comment]
README

**Comment by mariogamer2** [comment]
OK sorry

**Comment by mariogamer2** [comment]
http://pastebin.com/As9ghdw7

Give me this

**Comment by mariogamer2** [comment]
The main issues can be claused,but I create another one because of some things...
