### ISSUE TITLE
Cannot configure main-screen image display

### ISSUE THREAD

**Issue by ScrubEmperor** [yellows8/3ds_homemenuhax#88]
Exactly as the title says. I have the image want in the exact place where it should be, but when I try to set it, it says it failed to get the filesize. Which is weird cause I've done the same procedure in another one of my SD cards and it actually went through with it, but the second SD won't do it at all.

**Comment by yellows8** [comment]
If you really have the PNG at the location described in the README, maybe try formatting your SD FS.

**Comment by ScrubEmperor** [comment]
Sorry for the noob question but FS stands for...? File System?
Won't I lose all the stuff I've installed if I format it?

**Comment by RinMaru** [comment]
I wouldnt risk it if i lose all my stuff. using a picture is not that important lol

**Comment by ihaveamac** [comment]
you can simply back up the contents of your SD card, format it, and restore the backup

**Comment by ScrubEmperor** [comment]
Hmm I do have an emuNAND set up on both SD cards, so I assume I would have to back the emuNAND too right?
(I'm not really good with this stuff so yea I might be making some stupid questions)

**Comment by ihaveamac** [comment]
if you want to be safe, you should back it up in any case.

**Comment by yellows8** [comment]
Only the FAT-FS matters for this ...

**Comment by ScrubEmperor** [comment]
Ok thanks for your help!
