### ISSUE TITLE
Untested versions listed in the README

### ISSUE THREAD

**Issue by yellows8** [yellows8/3ds_homemenuhax#9]
Would be nice if those that have successfully setup + used themehax fine(no issues with the hblauncher-payload _itself_ either), would leave a comment here when the system-version is one listed as "not tested" in the README.

With release-archive v1.2, system-version v9.3 can't be successfully tested due to an installer issue with APT(#2), and v9.1j isn't supported by the hblauncher-payload to begin with at the time this issue was created.

**Comment by Hartie95** [comment]
9.0.0E new 3ds is working tor me, without any problem.

**Comment by yellows8** [comment]
Updated the README for that now, thanks.

**Comment by VicksDayQuil** [comment]
Can confirm NOT working with 9.7.0-25U on Old 3DS.
![snapchat-5312683833759213336](https://cloud.githubusercontent.com/assets/15291771/10712428/1152e848-7a69-11e5-9d78-2ce95b74f07d.jpg)

**Comment by yellows8** [comment]
No it works fine, you're just using the outdated installer(there's no official release with the fixed version yet).

**Comment by VicksDayQuil** [comment]
It works fine? How do I get it to work? (sorry I'm kind of a noob at this)

**Comment by yellows8** [comment]
It only works with builds from git, not <=v1.2.

**Comment by VicksDayQuil** [comment]
How would I go about obtaining that?

**Comment by yellows8** [comment]
Just wait for the next release if you can't build it yourself.

**Comment by Cydget** [comment]
I can confirm that the USA N3DS works on firmware 10.1.0.27 U, It works perfectly with homebrew launcher 2.1 but for homebrew launcer 2.5 there are problems(as to be expected).
