### ISSUE TITLE
Reverse changes for certain payloads that causes failures

### ISSUE THREAD

**Issue by n4ru** [yellows8/3ds_homemenuhax#91]
While this isn't exactly technical, I feel it would be best posted here as some people on GBATemp have anecdotally recorded that an older version of the payload loads significantly more often than the new one.

https://gbatemp.net/threads/guide-how-to-improve-menuhax-boot-rate-to-nearly-100.410764/

**Comment by yellows8** [comment]
"Reverse changes for certain payloads that causes failures"

This is just the payload _nothing_ to do with menuhax itself.

**Comment by n4ru** [comment]
Apologies for being naive, but who maintains the actual payloads used by menuhacks and do they have a repo?

**Comment by yellows8** [comment]
https://github.com/smealum/ninjhax2.x
