### ISSUE TITLE
lodepng error when trying to build only menuhax manager

### ISSUE THREAD

**Issue by mariogamer2** [yellows8/3ds_homemenuhax#92]
When trying to build menuhax manager only:

http://pastebin.com/LjKpD3BD

**Comment by yellows8** [comment]
Ignoring the README _again_ ......

**Comment by mariogamer2** [comment]
Ok sorry,the next time I'll totally read the Readme Sorry again...

**Comment by mariogamer2** [comment]
No the lodepng error are always here...
