### ISSUE TITLE
Old 3dsxl menuhax instillation error - http://i.imgur.com/B0yqSGK.jpg?1 

### ISSUE THREAD

**Issue by 01X2** [yellows8/3ds_homemenuhax#93]
Whenever I try to install menuhax I get this error, all the files are on the SD card, but It won't install.

Error: http://i.imgur.com/B0yqSGK.jpg?1

**Comment by yellows8** [comment]
Outdated release-archive .......

**Comment by 01X2** [comment]
Where can I get the latest version?

**Comment by Stepghad** [comment]
I'm getting the same error but with USA version not EUR. I'm using 2.2 which is apparently the latest release.

**Comment by yellows8** [comment]
@Stepghad  Screenshot?

**Comment by Stepghad** [comment]
![image](https://cloud.githubusercontent.com/assets/17309594/13160525/bde87b2e-d64c-11e5-9285-9c28f015f545.png)

O3DS Version: 10.3.0.28 U

**Comment by yellows8** [comment]
Can you verify that the .lz file it tries to access there actually exists on your SD?

**Comment by Stepghad** [comment]
Ok so I found a solution. All my files were in the folder named "Nintendo 3DS". I created a new folder on my SD card called "3ds", which is where the program looks for the .lz files. Basically I just moved the whole menuhax folder to the "3ds" folder and it installed fine after that. @flamekong You should see if this helps. I made sure to open the themes menu from the 3ds home menu so it would reconfigure the theme settings or whatever before going into homebrew and installing menuhax.
