### ISSUE TITLE
Can't install menuhax

### ISSUE THREAD

**Issue by DarthSyrius** [yellows8/3ds_homemenuhax#94]
Receiving that error again and again, a i'm trying for two 3 or 4 days and get the same error. Please help me.

I'm brazillian, sorry for any english error.

![foto](https://cloud.githubusercontent.com/assets/17303565/13126941/ead4d496-d5b3-11e5-857b-615c825eb90f.JPG)

**Comment by yellows8** [comment]
That error-code isn't documented on 3dbrew, but it's probably just network fail.
