### ISSUE TITLE
Error Code 0x00000002  |  problems installing on 2DS running 10.5.0-30

### ISSUE THREAD

**Issue by Xanjaxn** [yellows8/3ds_homemenuhax#95]
![win_20160218_18_38_58_pro](https://cloud.githubusercontent.com/assets/16702959/13161908/ef6a7784-d66e-11e5-8b3e-6f5f0a2bad2d.jpg)
I used browserhax to start the Homebrew Launcher, but whenever I try to install Menuhax, it shows the above message. I have the menuhax_manager directory in 2 different places: in D:/3ds, and in D:/Nintendo 3DS/3ds. I also pulled the shufflepayload folder and the themepayload folder out of the finaloutput folder, to duplicate the pathway shown in the error message. Please let me know if and/or how I can fix this. Thanks already for this amazing software

**Comment by yellows8** [comment]
Since this issue was created before this... https://github.com/yellows8/3ds_homemenuhax/blob/master/ISSUE_TEMPLATE.md

**Comment by diggitydiggitydue** [comment]
Has this issue been resolved?  I'm getting a similar error and reading through the README kinda has my head spinning on any section that isn't "Installation."  I was following the Plailect guide and ended up getting similar errors as xanjaxn.  I'm using an old 3dsxl 10.7.0-32 with OOTHax.  I usually start with the theme menu on the home screen then go to the OOTHax to boot to the home-brew menu.  Yet whenever I try to install menuhax I get this error message.  I grabbed the starter kit from https://smealum.github.io/3ds/ and followed instructions for everything that needed to go on my sd's root.  

If there's any additional information needed please let me know.  Any assistance is appreciated.  My apologies if the solution is clearly given in the Readme but i'm not familiar with most of the technical terms used.  Also you guys are amazing for doing all of this and even helping noobs like us with issues. Thank you for your time!

![screen shot 2016-04-01 at 2 32 45 am](https://cloud.githubusercontent.com/assets/18209686/14203437/c839459a-f7b2-11e5-917f-613c9a30e69a.png)

**Comment by yellows8** [comment]
"10.7.0-32" .............................. https://github.com/yellows8/3ds_homemenuhax#vuln-fix-sysupdates

**Comment by diggitydiggitydue** [comment]
ah. i can't do menuhax.  thank you pointing it out.
