### ISSUE TITLE
Error installing menuhax on old 3ds 10.5.0-30U

### ISSUE THREAD

**Issue by CubitoSenpai** [yellows8/3ds_homemenuhax#96]
[https://drive.google.com/file/d/0B232Fm1vI18yR2VZbmNqdWdCZWM/view?usp=sharing](https://drive.google.com/file/d/0B232Fm1vI18yR2VZbmNqdWdCZWM/view?usp=sharing)

**Comment by RinMaru** [comment]
No error for me it installs just fine o3ds 10.5U. Did you acess theme setting on 3ds at least once?
